//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reihitsu.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AnalyzerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AnalyzerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reihitsu.Analyzer.AnalyzerResources", typeof(AnalyzerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logical operator ! should not be used for clarity..
        /// </summary>
        internal static string RH0001MessageFormat {
            get {
                return ResourceManager.GetString("RH0001MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The logical operator ! should not be used for clarity..
        /// </summary>
        internal static string RH0001Title {
            get {
                return ResourceManager.GetString("RH0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not prefix calls with base. Unless a local implementation exists..
        /// </summary>
        internal static string RH0002MessageFormat {
            get {
                return ResourceManager.GetString("RH0002MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not prefix calls with base. Unless a local implementation exists..
        /// </summary>
        internal static string RH0002Title {
            get {
                return ResourceManager.GetString("RH0002Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must not contain empty statements..
        /// </summary>
        internal static string RH0003MessageFormat {
            get {
                return ResourceManager.GetString("RH0003MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code must not contain empty statements..
        /// </summary>
        internal static string RH0003Title {
            get {
                return ResourceManager.GetString("RH0003Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements must not use unnecessary parentheses..
        /// </summary>
        internal static string RH0004MessageFormat {
            get {
                return ResourceManager.GetString("RH0004MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statements must not use unnecessary parentheses..
        /// </summary>
        internal static string RH0004Title {
            get {
                return ResourceManager.GetString("RH0004Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments must contain text..
        /// </summary>
        internal static string RH0005MessageFormat {
            get {
                return ResourceManager.GetString("RH0005MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments must contain text..
        /// </summary>
        internal static string RH0005Title {
            get {
                return ResourceManager.GetString("RH0005Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use string.Empty for empty strings..
        /// </summary>
        internal static string RH0006MessageFormat {
            get {
                return ResourceManager.GetString("RH0006MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use string.Empty for empty strings..
        /// </summary>
        internal static string RH0006Title {
            get {
                return ResourceManager.GetString("RH0006Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use shorthand for nullable types..
        /// </summary>
        internal static string RH0007MessageFormat {
            get {
                return ResourceManager.GetString("RH0007MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use shorthand for nullable types..
        /// </summary>
        internal static string RH0007Title {
            get {
                return ResourceManager.GetString("RH0007Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use default value type constructor..
        /// </summary>
        internal static string RH0008MessageFormat {
            get {
                return ResourceManager.GetString("RH0008MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use default value type constructor..
        /// </summary>
        internal static string RH0008Title {
            get {
                return ResourceManager.GetString("RH0008Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use lambda syntax..
        /// </summary>
        internal static string RH0009MessageFormat {
            get {
                return ResourceManager.GetString("RH0009MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use lambda syntax..
        /// </summary>
        internal static string RH0009Title {
            get {
                return ResourceManager.GetString("RH0009Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use readable conditions..
        /// </summary>
        internal static string RH0010MessageFormat {
            get {
                return ResourceManager.GetString("RH0010MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use readable conditions..
        /// </summary>
        internal static string RH0010Title {
            get {
                return ResourceManager.GetString("RH0010Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional expressions must declare precedence..
        /// </summary>
        internal static string RH0011MessageFormat {
            get {
                return ResourceManager.GetString("RH0011MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional expressions must declare precedence..
        /// </summary>
        internal static string RH0011Title {
            get {
                return ResourceManager.GetString("RH0011Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not prefix local members with this..
        /// </summary>
        internal static string RH0012MessageFormat {
            get {
                return ResourceManager.GetString("RH0012MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not prefix local members with this..
        /// </summary>
        internal static string RH0012Title {
            get {
                return ResourceManager.GetString("RH0012Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use query syntax..
        /// </summary>
        internal static string RH0013MessageFormat {
            get {
                return ResourceManager.GetString("RH0013MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use query syntax..
        /// </summary>
        internal static string RH0013Title {
            get {
                return ResourceManager.GetString("RH0013Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private auto-implemented properties should not be used..
        /// </summary>
        internal static string RH0101MessageFormat {
            get {
                return ResourceManager.GetString("RH0101MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private auto-implemented properties should not be used..
        /// </summary>
        internal static string RH0101Title {
            get {
                return ResourceManager.GetString("RH0101Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async void methods should not be used..
        /// </summary>
        internal static string RH0102MessageFormat {
            get {
                return ResourceManager.GetString("RH0102MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Async void methods should not be used..
        /// </summary>
        internal static string RH0102Title {
            get {
                return ResourceManager.GetString("RH0102Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotImplementedException should not be used..
        /// </summary>
        internal static string RH0103MessageFormat {
            get {
                return ResourceManager.GetString("RH0103MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotImplementedException should not be used..
        /// </summary>
        internal static string RH0103Title {
            get {
                return ResourceManager.GetString("RH0103Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access modifier must be declared..
        /// </summary>
        internal static string RH0104MessageFormat {
            get {
                return ResourceManager.GetString("RH0104MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access modifier must be declared..
        /// </summary>
        internal static string RH0104Title {
            get {
                return ResourceManager.GetString("RH0104Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields must be private..
        /// </summary>
        internal static string RH0105MessageFormat {
            get {
                return ResourceManager.GetString("RH0105MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields must be private..
        /// </summary>
        internal static string RH0105Title {
            get {
                return ResourceManager.GetString("RH0105Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File may only contain a single namespace..
        /// </summary>
        internal static string RH0106MessageFormat {
            get {
                return ResourceManager.GetString("RH0106MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File may only contain a single namespace..
        /// </summary>
        internal static string RH0106Title {
            get {
                return ResourceManager.GetString("RH0106Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code analysis suppressions must have a justification..
        /// </summary>
        internal static string RH0107MessageFormat {
            get {
                return ResourceManager.GetString("RH0107MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code analysis suppressions must have a justification..
        /// </summary>
        internal static string RH0107Title {
            get {
                return ResourceManager.GetString("RH0107Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.Assert must provide message text..
        /// </summary>
        internal static string RH0108MessageFormat {
            get {
                return ResourceManager.GetString("RH0108MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.Assert must provide message text..
        /// </summary>
        internal static string RH0108Title {
            get {
                return ResourceManager.GetString("RH0108Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.Fail must provide message text..
        /// </summary>
        internal static string RH0109MessageFormat {
            get {
                return ResourceManager.GetString("RH0109MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.Fail must provide message text..
        /// </summary>
        internal static string RH0109Title {
            get {
                return ResourceManager.GetString("RH0109Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary delegate parentheses should be removed..
        /// </summary>
        internal static string RH0110MessageFormat {
            get {
                return ResourceManager.GetString("RH0110MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary delegate parentheses should be removed..
        /// </summary>
        internal static string RH0110Title {
            get {
                return ResourceManager.GetString("RH0110Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary attribute constructor parentheses should be removed..
        /// </summary>
        internal static string RH0111MessageFormat {
            get {
                return ResourceManager.GetString("RH0111MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary attribute constructor parentheses should be removed..
        /// </summary>
        internal static string RH0111Title {
            get {
                return ResourceManager.GetString("RH0111Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the class/struct/enum should match the filename..
        /// </summary>
        internal static string RH0201MessageFormat {
            get {
                return ResourceManager.GetString("RH0201MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the class/struct/enum should match the filename..
        /// </summary>
        internal static string RH0201Title {
            get {
                return ResourceManager.GetString("RH0201Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class names should be in PascalCase.
        /// </summary>
        internal static string RH0202MessageFormat {
            get {
                return ResourceManager.GetString("RH0202MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class names should be in PascalCase.
        /// </summary>
        internal static string RH0202Title {
            get {
                return ResourceManager.GetString("RH0202Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct names should be in PascalCase.
        /// </summary>
        internal static string RH0203MessageFormat {
            get {
                return ResourceManager.GetString("RH0203MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Struct names should be in PascalCase.
        /// </summary>
        internal static string RH0203Title {
            get {
                return ResourceManager.GetString("RH0203Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration names should be in PascalCase.
        /// </summary>
        internal static string RH0204MessageFormat {
            get {
                return ResourceManager.GetString("RH0204MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration names should be in PascalCase.
        /// </summary>
        internal static string RH0204Title {
            get {
                return ResourceManager.GetString("RH0204Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration members names should be in PascalCase.
        /// </summary>
        internal static string RH0205MessageFormat {
            get {
                return ResourceManager.GetString("RH0205MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enumeration members names should be in PascalCase.
        /// </summary>
        internal static string RH0205Title {
            get {
                return ResourceManager.GetString("RH0205Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface names should be in PascalCase.
        /// </summary>
        internal static string RH0206MessageFormat {
            get {
                return ResourceManager.GetString("RH0206MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface names should be in PascalCase.
        /// </summary>
        internal static string RH0206Title {
            get {
                return ResourceManager.GetString("RH0206Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event names should be in PascalCase.
        /// </summary>
        internal static string RH0207MessageFormat {
            get {
                return ResourceManager.GetString("RH0207MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event names should be in PascalCase.
        /// </summary>
        internal static string RH0207Title {
            get {
                return ResourceManager.GetString("RH0207Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate names should be in PascalCase.
        /// </summary>
        internal static string RH0208MessageFormat {
            get {
                return ResourceManager.GetString("RH0208MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate names should be in PascalCase.
        /// </summary>
        internal static string RH0208Title {
            get {
                return ResourceManager.GetString("RH0208Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method members names should be in PascalCase.
        /// </summary>
        internal static string RH0209MessageFormat {
            get {
                return ResourceManager.GetString("RH0209MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method members names should be in PascalCase.
        /// </summary>
        internal static string RH0209Title {
            get {
                return ResourceManager.GetString("RH0209Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local function names should be in PascalCase.
        /// </summary>
        internal static string RH0210MessageFormat {
            get {
                return ResourceManager.GetString("RH0210MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local function names should be in PascalCase.
        /// </summary>
        internal static string RH0210Title {
            get {
                return ResourceManager.GetString("RH0210Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method parameter names should be in camelCase.
        /// </summary>
        internal static string RH0211MessageFormat {
            get {
                return ResourceManager.GetString("RH0211MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method parameter names should be in camelCase.
        /// </summary>
        internal static string RH0211Title {
            get {
                return ResourceManager.GetString("RH0211Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private field names should be in _camelCase.
        /// </summary>
        internal static string RH0212MessageFormat {
            get {
                return ResourceManager.GetString("RH0212MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private field names should be in _camelCase.
        /// </summary>
        internal static string RH0212Title {
            get {
                return ResourceManager.GetString("RH0212Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected field names should be in _camelCase.
        /// </summary>
        internal static string RH0213MessageFormat {
            get {
                return ResourceManager.GetString("RH0213MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected field names should be in _camelCase.
        /// </summary>
        internal static string RH0213Title {
            get {
                return ResourceManager.GetString("RH0213Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal field names should be in PascalCase.
        /// </summary>
        internal static string RH0214MessageFormat {
            get {
                return ResourceManager.GetString("RH0214MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal field names should be in PascalCase.
        /// </summary>
        internal static string RH0214Title {
            get {
                return ResourceManager.GetString("RH0214Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public field names should be in PascalCase.
        /// </summary>
        internal static string RH0215MessageFormat {
            get {
                return ResourceManager.GetString("RH0215MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public field names should be in PascalCase.
        /// </summary>
        internal static string RH0215Title {
            get {
                return ResourceManager.GetString("RH0215Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Const field names should be in PascalCase.
        /// </summary>
        internal static string RH0216MessageFormat {
            get {
                return ResourceManager.GetString("RH0216MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Const field names should be in PascalCase.
        /// </summary>
        internal static string RH0216Title {
            get {
                return ResourceManager.GetString("RH0216Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private property names should be in PascalCase.
        /// </summary>
        internal static string RH0217MessageFormat {
            get {
                return ResourceManager.GetString("RH0217MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private property names should be in PascalCase.
        /// </summary>
        internal static string RH0217Title {
            get {
                return ResourceManager.GetString("RH0217Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected property names should be in PascalCase.
        /// </summary>
        internal static string RH0218MessageFormat {
            get {
                return ResourceManager.GetString("RH0218MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected property names should be in PascalCase.
        /// </summary>
        internal static string RH0218Title {
            get {
                return ResourceManager.GetString("RH0218Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal property names should be in PascalCase.
        /// </summary>
        internal static string RH0219MessageFormat {
            get {
                return ResourceManager.GetString("RH0219MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal property names should be in PascalCase.
        /// </summary>
        internal static string RH0219Title {
            get {
                return ResourceManager.GetString("RH0219Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public property names should be in PascalCase.
        /// </summary>
        internal static string RH0220MessageFormat {
            get {
                return ResourceManager.GetString("RH0220MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public property names should be in PascalCase.
        /// </summary>
        internal static string RH0220Title {
            get {
                return ResourceManager.GetString("RH0220Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variables should be in camelCase.
        /// </summary>
        internal static string RH0221MessageFormat {
            get {
                return ResourceManager.GetString("RH0221MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local variable names should be in camelCase.
        /// </summary>
        internal static string RH0221Title {
            get {
                return ResourceManager.GetString("RH0221Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named tuple elements should be in PascalCase.
        /// </summary>
        internal static string RH0222MessageFormat {
            get {
                return ResourceManager.GetString("RH0222MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named tuple elements should be in PascalCase.
        /// </summary>
        internal static string RH0222Title {
            get {
                return ResourceManager.GetString("RH0222Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables in deconstruction should be in camelCase.
        /// </summary>
        internal static string RH0223MessageFormat {
            get {
                return ResourceManager.GetString("RH0223MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deconstruction variable names should be in camelCase.
        /// </summary>
        internal static string RH0223Title {
            get {
                return ResourceManager.GetString("RH0223Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named tuple argument names should be in PascalCase.
        /// </summary>
        internal static string RH0224MessageFormat {
            get {
                return ResourceManager.GetString("RH0224MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named tuple argument names should be in PascalCase.
        /// </summary>
        internal static string RH0224Title {
            get {
                return ResourceManager.GetString("RH0224Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces should be in PascalCase.
        /// </summary>
        internal static string RH0225MessageFormat {
            get {
                return ResourceManager.GetString("RH0225MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces should be in PascalCase.
        /// </summary>
        internal static string RH0225Title {
            get {
                return ResourceManager.GetString("RH0225Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces should be in PascalCase.
        /// </summary>
        internal static string RH0226MessageFormat {
            get {
                return ResourceManager.GetString("RH0226MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespaces should be in PascalCase.
        /// </summary>
        internal static string RH0226Title {
            get {
                return ResourceManager.GetString("RH0226Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given namespace is not allowed (see reihitsu.json).
        /// </summary>
        internal static string RH0227MessageFormat {
            get {
                return ResourceManager.GetString("RH0227MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given namespace is not allowed (see reihitsu.json).
        /// </summary>
        internal static string RH0227Title {
            get {
                return ResourceManager.GetString("RH0227Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Static readonly field names should be in PascalCase.
        /// </summary>
        internal static string RH0228MessageFormat {
            get {
                return ResourceManager.GetString("RH0228MessageFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Static readonly field names should be in PascalCase.
        /// </summary>
        internal static string RH0228Title {
            get {
                return ResourceManager.GetString("RH0228Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the #region and #endregion should match..
        /// </summary>
        internal static string RH0301MessageFormat {
            get {
                return ResourceManager.GetString("RH0301MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the #region and #endregion should match..
        /// </summary>
        internal static string RH0301Title {
            get {
                return ResourceManager.GetString("RH0301Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object initializer should be formatted correctly..
        /// </summary>
        internal static string RH0302MessageFormat {
            get {
                return ResourceManager.GetString("RH0302MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object initializer should be formatted correctly..
        /// </summary>
        internal static string RH0302Title {
            get {
                return ResourceManager.GetString("RH0302Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The try-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0303MessageFormat {
            get {
                return ResourceManager.GetString("RH0303MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The try-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0303Title {
            get {
                return ResourceManager.GetString("RH0303Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The if-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0304MessageFormat {
            get {
                return ResourceManager.GetString("RH0304MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The if-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0304Title {
            get {
                return ResourceManager.GetString("RH0304Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The while-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0305MessageFormat {
            get {
                return ResourceManager.GetString("RH0305MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The while-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0305Title {
            get {
                return ResourceManager.GetString("RH0305Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The do-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0306MessageFormat {
            get {
                return ResourceManager.GetString("RH0306MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The do-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0306Title {
            get {
                return ResourceManager.GetString("RH0306Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The using-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0307MessageFormat {
            get {
                return ResourceManager.GetString("RH0307MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The using-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0307Title {
            get {
                return ResourceManager.GetString("RH0307Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreach-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0308MessageFormat {
            get {
                return ResourceManager.GetString("RH0308MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The foreach-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0308Title {
            get {
                return ResourceManager.GetString("RH0308Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The for-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0309MessageFormat {
            get {
                return ResourceManager.GetString("RH0309MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The for-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0309Title {
            get {
                return ResourceManager.GetString("RH0309Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0310MessageFormat {
            get {
                return ResourceManager.GetString("RH0310MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The return-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0310Title {
            get {
                return ResourceManager.GetString("RH0310Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goto-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0311MessageFormat {
            get {
                return ResourceManager.GetString("RH0311MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The goto-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0311Title {
            get {
                return ResourceManager.GetString("RH0311Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The break-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0312MessageFormat {
            get {
                return ResourceManager.GetString("RH0312MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The break-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0312Title {
            get {
                return ResourceManager.GetString("RH0312Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The break-Statement should be followed by a blank line..
        /// </summary>
        internal static string RH0313MessageFormat {
            get {
                return ResourceManager.GetString("RH0313MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The break-Statement should be followed by a blank line..
        /// </summary>
        internal static string RH0313Title {
            get {
                return ResourceManager.GetString("RH0313Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The continue-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0314MessageFormat {
            get {
                return ResourceManager.GetString("RH0314MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The continue-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0314Title {
            get {
                return ResourceManager.GetString("RH0314Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The throw-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0315MessageFormat {
            get {
                return ResourceManager.GetString("RH0315MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The throw-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0315Title {
            get {
                return ResourceManager.GetString("RH0315Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The switch-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0316MessageFormat {
            get {
                return ResourceManager.GetString("RH0316MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The switch-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0316Title {
            get {
                return ResourceManager.GetString("RH0316Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checked-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0317MessageFormat {
            get {
                return ResourceManager.GetString("RH0317MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The checked-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0317Title {
            get {
                return ResourceManager.GetString("RH0317Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unchecked-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0318MessageFormat {
            get {
                return ResourceManager.GetString("RH0318MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unchecked-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0318Title {
            get {
                return ResourceManager.GetString("RH0318Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fixed-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0319MessageFormat {
            get {
                return ResourceManager.GetString("RH0319MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fixed-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0319Title {
            get {
                return ResourceManager.GetString("RH0319Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lock-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0320MessageFormat {
            get {
                return ResourceManager.GetString("RH0320MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The lock-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0320Title {
            get {
                return ResourceManager.GetString("RH0320Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The yield-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0321MessageFormat {
            get {
                return ResourceManager.GetString("RH0321MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The yield-Statement should be preceded by a blank line..
        /// </summary>
        internal static string RH0321Title {
            get {
                return ResourceManager.GetString("RH0321Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method chains should be aligned..
        /// </summary>
        internal static string RH0324MessageFormat {
            get {
                return ResourceManager.GetString("RH0324MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method chains should be aligned..
        /// </summary>
        internal static string RH0324Title {
            get {
                return ResourceManager.GetString("RH0324Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression style methods should not be used..
        /// </summary>
        internal static string RH0325MessageFormat {
            get {
                return ResourceManager.GetString("RH0325MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression style methods should not be used..
        /// </summary>
        internal static string RH0325Title {
            get {
                return ResourceManager.GetString("RH0325Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression style constructors should not be used..
        /// </summary>
        internal static string RH0326MessageFormat {
            get {
                return ResourceManager.GetString("RH0326MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression style constructors should not be used..
        /// </summary>
        internal static string RH0326Title {
            get {
                return ResourceManager.GetString("RH0326Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression style get-only properties should be single lined..
        /// </summary>
        internal static string RH0327MessageFormat {
            get {
                return ResourceManager.GetString("RH0327MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression style get-only properties should be single lined..
        /// </summary>
        internal static string RH0327Title {
            get {
                return ResourceManager.GetString("RH0327Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the #region should start with an uppercase letter..
        /// </summary>
        internal static string RH0328MessageFormat {
            get {
                return ResourceManager.GetString("RH0328MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the #region should start with an uppercase letter..
        /// </summary>
        internal static string RH0328Title {
            get {
                return ResourceManager.GetString("RH0328Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical expressions should be formatted correctly..
        /// </summary>
        internal static string RH0329MessageFormat {
            get {
                return ResourceManager.GetString("RH0329MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical expressions should be formatted correctly..
        /// </summary>
        internal static string RH0329Title {
            get {
                return ResourceManager.GetString("RH0329Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw string literals should be formatted correctly..
        /// </summary>
        internal static string RH0330MessageFormat {
            get {
                return ResourceManager.GetString("RH0330MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw string literals should be formatted correctly..
        /// </summary>
        internal static string RH0330Title {
            get {
                return ResourceManager.GetString("RH0330Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first argument should be on the same line as the opening parenthesis..
        /// </summary>
        internal static string RH0331MessageFormat {
            get {
                return ResourceManager.GetString("RH0331MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first argument should be on the same line as the opening parenthesis..
        /// </summary>
        internal static string RH0331Title {
            get {
                return ResourceManager.GetString("RH0331Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments should either all be on one line or each on its own line..
        /// </summary>
        internal static string RH0332MessageFormat {
            get {
                return ResourceManager.GetString("RH0332MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments should either all be on one line or each on its own line..
        /// </summary>
        internal static string RH0332Title {
            get {
                return ResourceManager.GetString("RH0332Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-line arguments should be aligned..
        /// </summary>
        internal static string RH0333MessageFormat {
            get {
                return ResourceManager.GetString("RH0333MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-line arguments should be aligned..
        /// </summary>
        internal static string RH0333Title {
            get {
                return ResourceManager.GetString("RH0333Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# source files should be encoded as UTF-8 with BOM..
        /// </summary>
        internal static string RH0334MessageFormat {
            get {
                return ResourceManager.GetString("RH0334MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# source files should be encoded as UTF-8 with BOM..
        /// </summary>
        internal static string RH0334Title {
            get {
                return ResourceManager.GetString("RH0334Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The \&lt;inheritdoc/&gt; Tag should be used if possible..
        /// </summary>
        internal static string RH0401MessageFormat {
            get {
                return ResourceManager.GetString("RH0401MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The \&lt;inheritdoc/&gt; Tag should be used if possible..
        /// </summary>
        internal static string RH0401Title {
            get {
                return ResourceManager.GetString("RH0401Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types used as keys must implement equality members..
        /// </summary>
        internal static string RH0501MessageFormat {
            get {
                return ResourceManager.GetString("RH0501MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types used as keys must implement equality members..
        /// </summary>
        internal static string RH0501Title {
            get {
                return ResourceManager.GetString("RH0501Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types used for equality comparison must implement equality members.
        /// </summary>
        internal static string RH0502MessageFormat {
            get {
                return ResourceManager.GetString("RH0502MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types used for equality comparison must implement equality members.
        /// </summary>
        internal static string RH0502Title {
            get {
                return ResourceManager.GetString("RH0502Title", resourceCulture);
            }
        }
    }
}
