//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reihitsu.Analyzer.Test.Formatting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reihitsu.Analyzer.Test.Formatting.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Reihitsu.Analyzer.Test.Design.Resources
        ///{
        ///    internal class RH0101
        ///    {
        ///        #region Fields
        ///        private bool _field;
        ///        #endregion // Fields
        ///        #region Properties
        ///
        ///        public bool Property { get { return _field; } }
        ///
        ///        #endregion // Properties
        ///
        ///        #region Methods
        ///
        ///        public bool GetValue() =&gt; _field;
        ///
        ///        #endregion // Methods
        ///    }
        ///}.
        /// </summary>
        internal static string RH0301_ResultData {
            get {
                return ResourceManager.GetString("RH0301_ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Reihitsu.Analyzer.Test.Design.Resources
        ///{
        ///    internal class RH0101
        ///    {
        ///        #region Fields
        ///        private bool _field;
        ///        {|#0:#endregion Fields|}
        ///        #region Properties
        ///
        ///        public bool Property { get { return _field; } }
        ///
        ///        {|#1:#endregion // Fields|}
        ///
        ///        #region Methods
        ///
        ///        public bool GetValue() =&gt; _field;
        ///
        ///        #endregion // Methods
        ///    }
        ///}.
        /// </summary>
        internal static string RH0301_TestData {
            get {
                return ResourceManager.GetString("RH0301_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Reihitsu.Analyzer.Test.Design.Resources
        ///{
        ///    internal class RH0301
        ///    {
        ///        public RH0301()
        ///        {
        ///            var tmp = new RH0301
        ///                      {
        ///                          Test = &quot;123&quot;
        ///                      };
        ///        }
        ///
        ///        public string Test { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0302_ResultData {
            get {
                return ResourceManager.GetString("RH0302_ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Reihitsu.Analyzer.Test.Design.Resources
        ///{
        ///    internal class RH0301
        ///    {
        ///        public RH0301()
        ///        {
        ///            var tmp = new RH0301
        ///            {|#0:{
        ///                Test = &quot;123&quot;
        ///            };|}
        ///        }
        ///
        ///        public string Test { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0302_TestData {
            get {
                return ResourceManager.GetString("RH0302_TestData", resourceCulture);
            }
        }
    }
}
