//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reihitsu.Analyzer.Test.Formatting.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reihitsu.Analyzer.Test.Formatting.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Reihitsu.Analyzer.Test.Design.Resources
        ///{
        ///    internal class RH0101
        ///    {
        ///        #region Fields
        ///        private bool _field;
        ///        #endregion // Fields
        ///        #region Properties
        ///
        ///        public bool Property { get { return _field; } }
        ///
        ///        #endregion // Properties
        ///
        ///        #region Methods
        ///
        ///        public bool GetValue() =&gt; _field;
        ///
        ///        #endregion // Methods
        ///
        ///        #region Outer 1
        ///
        ///        #re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RH0301_ResultData {
            get {
                return ResourceManager.GetString("RH0301_ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Reihitsu.Analyzer.Test.Design.Resources
        ///{
        ///    internal class RH0101
        ///    {
        ///        #region Fields
        ///        private bool _field;
        ///        {|#0:#endregion Fields|}
        ///        #region Properties
        ///
        ///        public bool Property { get { return _field; } }
        ///
        ///        {|#1:#endregion // Fields|}
        ///
        ///        #region Methods
        ///
        ///        public bool GetValue() =&gt; _field;
        ///
        ///        #endregion // Methods
        ///
        ///        #region Outer 1
        ///
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RH0301_TestData {
            get {
                return ResourceManager.GetString("RH0301_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Reihitsu.Analyzer.Test.Design.Resources
        ///{
        ///    internal class RH0301
        ///    {
        ///        public RH0301()
        ///        {
        ///            var tmp1 = new RH0301
        ///                       {
        ///                           Test = &quot;123&quot;
        ///                       };
        ///
        ///            var tmp2 = new RH0301
        ///                       {
        ///                           Test = &quot;123&quot;
        ///                       };
        ///
        ///            var tmp3 = new RH0301
        ///                    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RH0302_ResultData {
            get {
                return ResourceManager.GetString("RH0302_ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace Reihitsu.Analyzer.Test.Design.Resources
        ///{
        ///    internal class RH0301
        ///    {
        ///        public RH0301()
        ///        {
        ///            var tmp1 = {|#0:new RH0301
        ///            {
        ///                Test = &quot;123&quot;
        ///            }|};
        ///
        ///            var tmp2 = {|#1:new RH0301
        ///                       {
        ///                Test = &quot;123&quot;
        ///                       }|};
        ///
        ///            var tmp3 = {|#2:new RH0301
        ///                                         {
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RH0302_TestData {
            get {
                return ResourceManager.GetString("RH0302_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0303
        ///{
        ///    public RH0303()
        ///    {
        ///        try
        ///        {
        ///        }
        ///        catch
        ///        {
        ///        }
        ///        {|#0:try|}
        ///        {
        ///        }
        ///        catch
        ///        {
        ///        }
        ///
        ///        try
        ///        {
        ///        }
        ///        catch
        ///        {
        ///        }
        ///        // Test
        ///        try
        ///        {
        ///        }
        ///        catch
        ///        {
        ///        }
        ///        /* Test */
        ///        try
        ///        {
        ///        }
        ///        catch
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0303_TestData {
            get {
                return ResourceManager.GetString("RH0303_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0304
        ///{
        ///    public RH0304()
        ///    {
        ///        if (true)
        ///        {
        ///        }
        ///        {|#0:if|} (true)
        ///        {
        ///        }
        ///
        ///        if (true)
        ///        {
        ///        }
        ///        // Test
        ///        if (true)
        ///        {
        ///        }
        ///        /* Test */
        ///        if (true)
        ///        {
        ///        }
        ///        else if (true)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0304_TestData {
            get {
                return ResourceManager.GetString("RH0304_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0305
        ///{
        ///    public RH0305()
        ///    {
        ///        while (true)
        ///        {
        ///        }
        ///        {|#0:while|} (true)
        ///        {
        ///        }
        ///
        ///        while (true)
        ///        {
        ///        }
        ///        // Test
        ///        while (true)
        ///        {
        ///        }
        ///        /* Test */
        ///        while (true)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0305_TestData {
            get {
                return ResourceManager.GetString("RH0305_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0306
        ///{
        ///    public RH0306()
        ///    {
        ///        do
        ///        {
        ///        } while (true);
        ///        {|#0:do|}
        ///        {
        ///        } while (true);
        ///
        ///        do
        ///        {
        ///        } while (true);
        ///        // Test
        ///        do
        ///        {
        ///        } while (true);
        ///        /* Test */
        ///        do
        ///        {
        ///        } while (true);
        ///    }
        ///}.
        /// </summary>
        internal static string RH0306_TestData {
            get {
                return ResourceManager.GetString("RH0306_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0307
        ///{
        ///    public async void Test()
        ///    {
        ///        using (var resource = new System.IO.MemoryStream())
        ///        {
        ///        }
        ///        {|#0:using|} (var resource = new System.IO.MemoryStream())
        ///        {
        ///        }
        ///
        ///        using (var resource = new System.IO.MemoryStream())
        ///        {
        ///        }
        ///        // Test
        ///        using (var resource = new System.IO.MemoryStream())
        ///        {
        ///        }
        ///        /* Test */
        ///        using (var resource = new System.IO.MemoryStream())
        ///        {        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RH0307_TestData {
            get {
                return ResourceManager.GetString("RH0307_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0308
        ///{
        ///    private System.Collections.Generic.IAsyncEnumerable&lt;int&gt; _enumerable;
        ///    
        ///    public async void Test()
        ///    {
        ///        foreach (var item in new int[0])
        ///        {
        ///        }
        ///        {|#0:foreach|} (var item in new int[0])
        ///        {
        ///        }
        ///
        ///        foreach (var item in new int[0])
        ///        {
        ///        }
        ///        // Test
        ///        foreach (var item in new int[0])
        ///        {
        ///        }
        ///        /* Test */
        ///        foreach (var item in new int[0])
        ///        {
        ///        }
        ///
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RH0308_TestData {
            get {
                return ResourceManager.GetString("RH0308_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0309
        ///{
        ///    public RH0309()
        ///    {
        ///        for (int i = 0; i &lt; 10; i++)
        ///        {
        ///        }
        ///        {|#0:for|} (int i = 0; i &lt; 10; i++)
        ///        {
        ///        }
        ///
        ///        for (int i = 0; i &lt; 10; i++)
        ///        {
        ///        }
        ///        // Test
        ///        for (int i = 0; i &lt; 10; i++)
        ///        {
        ///        }
        ///        /* Test */
        ///        for (int i = 0; i &lt; 10; i++)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0309_TestData {
            get {
                return ResourceManager.GetString("RH0309_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0310
        ///{
        ///    public RH0310()
        ///    {
        ///        return;
        ///        {|#0:return|};
        ///
        ///        return;
        ///        // Test
        ///        return;
        ///        /* Test */
        ///        return;
        ///            
        ///            
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                return;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0310_TestData {
            get {
                return ResourceManager.GetString("RH0310_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0311
        ///{
        ///    public RH0311()
        ///    {
        ///        goto Label;
        ///        {|#0:goto|} Label;
        ///
        ///        goto Label;
        ///        // Test
        ///        goto Label;
        ///        /* Test */
        ///        goto Label;
        ///
        ///        Label:
        ///        return;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0311_TestData {
            get {
                return ResourceManager.GetString("RH0311_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0312
        ///{
        ///    public RH0312()
        ///    {
        ///        while (true)
        ///        { 
        ///            break;
        ///            {|#0:break|};
        ///
        ///            break;
        ///            // Test
        ///            break;
        ///            /* Test */
        ///            break;
        ///        }
        ///            
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                break;
        ///        }
        ///
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                System.Console.WriteLine();
        ///                break;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0312_TestData {
            get {
                return ResourceManager.GetString("RH0312_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0313
        ///{
        ///    public RH0313()
        ///    {
        ///        while(true)
        ///        {
        ///            break;
        ///            
        ///            {|#0:break|};
        ///            break;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0313_TestData {
            get {
                return ResourceManager.GetString("RH0313_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0314
        ///{
        ///    public RH0314()
        ///    {
        ///        while (true)
        ///        {   
        ///            continue;
        ///            {|#0:continue|};
        ///
        ///            continue;
        ///            // Test
        ///            continue;
        ///            /* Test */
        ///            continue;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0314_TestData {
            get {
                return ResourceManager.GetString("RH0314_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0315
        ///{
        ///    public RH0315()
        ///    {
        ///        throw new System.Exception();
        ///        {|#0:throw|} new System.Exception();
        ///
        ///        throw new System.Exception();
        ///        // Test
        ///        throw new System.Exception();
        ///        /* Test */
        ///        throw new System.Exception();
        ///
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                throw new System.Exception();
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0315_TestData {
            get {
                return ResourceManager.GetString("RH0315_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0316
        ///{
        ///    public RH0316()
        ///    {
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                break;
        ///        }
        ///        {|#0:switch|} (1)
        ///        {
        ///            case 1:
        ///            break;
        ///        }
        ///
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                break;
        ///        }
        ///        // Test
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                break;
        ///        }
        ///        /* Test */
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RH0316_TestData {
            get {
                return ResourceManager.GetString("RH0316_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0317
        ///{
        ///    public RH0317()
        ///    {
        ///        checked
        ///        {
        ///        }
        ///        {|#0:checked|}
        ///        {
        ///        }
        ///
        ///        checked
        ///        {
        ///        }
        ///        // Test
        ///        checked
        ///        {
        ///        }
        ///        /* Test */
        ///        checked
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0317_TestData {
            get {
                return ResourceManager.GetString("RH0317_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0318
        ///{
        ///    public RH0318()
        ///    {
        ///        unchecked
        ///        {
        ///        }
        ///        {|#0:unchecked|}
        ///        {
        ///        }
        ///
        ///        unchecked
        ///        {
        ///        }
        ///        // Test
        ///        unchecked
        ///        {
        ///        }
        ///        /* Test */
        ///        unchecked
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0318_TestData {
            get {
                return ResourceManager.GetString("RH0318_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0319
        ///{
        ///    public unsafe RH0319()
        ///    {
        ///        fixed (byte* ptr = stackalloc byte[10])
        ///        {
        ///        }
        ///        {|#0:fixed|} (byte* ptr = stackalloc byte[10])
        ///        {
        ///        }
        ///
        ///        fixed (byte* ptr = stackalloc byte[10])
        ///        {
        ///        }
        ///        // Test
        ///        fixed (byte* ptr = stackalloc byte[10])
        ///        {
        ///        }
        ///        /* Test */
        ///        fixed (byte* ptr = stackalloc byte[10])
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0319_TestData {
            get {
                return ResourceManager.GetString("RH0319_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0320
        ///{
        ///    private static object _lock = new object();
        ///    
        ///    public RH0320()
        ///    {
        ///        lock (_lock)
        ///        {
        ///        }
        ///        {|#0:lock|} (_lock)
        ///        {
        ///        }
        ///
        ///        lock (_lock)
        ///        {
        ///        }
        ///        // Test
        ///        lock (_lock)
        ///        {
        ///        }
        ///        /* Test */
        ///        lock (_lock)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0320_TestData {
            get {
                return ResourceManager.GetString("RH0320_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0321
        ///{
        ///    public System.Collections.Generic.IEnumerable&lt;int&gt; YieldReturn()
        ///    {
        ///        yield return 1;
        ///        {|#0:yield|} return 1;
        ///
        ///        yield return 1;
        ///        // Test
        ///        yield return 1;
        ///        /* Test */
        ///        yield return 1;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0321_TestData {
            get {
                return ResourceManager.GetString("RH0321_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0325
        ///{
        ///    {|#0:public int GetValueExpression() =&gt; 42;|}
        ///    
        ///    public int GetValueBlock()
        ///    {
        ///        return 42;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0325_TestData {
            get {
                return ResourceManager.GetString("RH0325_TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class RH0326
        ///{
        ///    {|#0:public RH0326() =&gt; System.Console.WriteLine();|}
        ///    {|#0:public RH0326(int i) =&gt; System.Console.WriteLine(i);|}
        ///    
        ///}
        ///
        ///internal class RH0326Expression
        ///{   
        ///    public RH0326()
        ///    {
        ///        System.Console.WriteLine();
        ///    }
        ///
        ///    public RH0326(int i)
        ///    {
        ///        System.Console.WriteLine(i);
        ///    }
        ///}.
        /// </summary>
        internal static string RH0326_TestData {
            get {
                return ResourceManager.GetString("RH0326_TestData", resourceCulture);
            }
        }
    }
}
