using System.Collections.Generic;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Reihitsu.Formatter;

/// <summary>
/// Helper methods for the <see cref="ReihitsuFormatter"/> class
/// </summary>
internal static class ReihitsuFormatterHelpers
{
    #region Methods

    /// <summary>
    /// Detects the predominant end-of-line sequence in the syntax node.
    /// Falls back to <see cref="Environment.NewLine"/> if no end-of-line trivia is found
    /// </summary>
    /// <param name="node">The syntax node to analyze</param>
    /// <returns>The detected end-of-line sequence</returns>
    internal static string DetectEndOfLine(SyntaxNode node)
    {
        var endOfLines = node.DescendantTrivia(descendIntoTrivia: true)
                             .Where(static trivia => trivia.IsKind(SyntaxKind.EndOfLineTrivia))
                             .Select(static trivia => trivia.ToString())
                             .ToList();

        if (endOfLines.Count == 0)
        {
            return Environment.NewLine;
        }

        var counts = new Dictionary<string, int>(StringComparer.Ordinal);

        foreach (var endOfLine in endOfLines)
        {
            counts[endOfLine] = counts.TryGetValue(endOfLine, out var count)
                                    ? count + 1
                                    : 1;
        }

        var predominantCount = counts.Values.Max();

        foreach (var endOfLine in endOfLines)
        {
            if (counts[endOfLine] == predominantCount)
            {
                return endOfLine;
            }
        }

        return Environment.NewLine;
    }

    /// <summary>
    /// Checks whether the syntax tree contains any syntax errors.
    /// Files with syntax errors are skipped by the formatter
    /// </summary>
    /// <param name="syntaxTree">The syntax tree to check</param>
    /// <returns><see langword="true"/> if the tree has error-level diagnostics; otherwise, <see langword="false"/></returns>
    internal static bool HasSyntaxErrors(SyntaxTree syntaxTree)
    {
        return syntaxTree.GetDiagnostics()
                         .Any(d => d.Severity == DiagnosticSeverity.Error);
    }

    /// <summary>
    /// Checks whether the source file is marked as auto-generated.
    /// Supports both single-line and multi-line comments containing
    /// the &lt;auto-generated /&gt; marker
    /// </summary>
    /// <param name="root">The syntax root to inspect</param>
    /// <returns><see langword="true"/> if an auto-generated marker is present; otherwise, <see langword="false"/></returns>
    internal static bool IsAutoGeneratedSource(SyntaxNode root)
    {
        var triviaList = root.DescendantTrivia(descendIntoTrivia: true);

        foreach (var trivia in triviaList)
        {
            if (IsCommentTrivia(trivia) == false)
            {
                continue;
            }

            if (ContainsAutoGeneratedMarker(trivia.ToString()))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Computes the base indentation level of a node from its position in the syntax tree.
    /// Walks the parent chain and counts indenting constructs (types, namespaces, blocks, etc.)
    /// </summary>
    /// <param name="node">The node whose base indentation level to compute</param>
    /// <returns>The number of indenting ancestor constructs</returns>
    internal static int ComputeBaseIndentLevel(SyntaxNode node)
    {
        var spanStart = node.SpanStart;
        var level = 0;
        var parent = node.Parent;

        while (parent != null)
        {
            if (IsIndentingAncestor(parent, spanStart))
            {
                level++;
            }

            parent = parent.Parent;
        }

        return level;
    }

    /// <summary>
    /// Computes the zero-based column position of a token within a syntax root
    /// by scanning backwards from the token's start position to the beginning of the line
    /// </summary>
    /// <param name="token">The token whose column to compute</param>
    /// <param name="root">The syntax root containing the token</param>
    /// <returns>The zero-based column position of the token</returns>
    internal static int ComputeTokenColumn(SyntaxToken token, SyntaxNode root)
    {
        var fullText = root.ToFullString();
        var position = token.SpanStart;
        var lineStart = position;

        while (lineStart > 0 && fullText[lineStart - 1] != '\n')
        {
            lineStart--;
        }

        return position - lineStart;
    }

    /// <summary>
    /// Adjusts the indentation of all tokens within a node that start on a new line
    /// by the given column offset
    /// </summary>
    /// <param name="node">The syntax node whose indentation to adjust</param>
    /// <param name="columnOffset">The number of columns to shift (positive = right, negative = left)</param>
    /// <returns>A new syntax node with adjusted indentation</returns>
    internal static SyntaxNode AdjustNodeIndentation(SyntaxNode node, int columnOffset)
    {
        var tokensOnNewLine = new List<SyntaxToken>();
        var afterEndOfLine = new Dictionary<SyntaxToken, bool>();

        foreach (var token in node.DescendantTokens())
        {
            if (StartsOnNewLine(token) == false)
            {
                continue;
            }

            tokensOnNewLine.Add(token);
            afterEndOfLine[token] = IsAfterEndOfLine(token);
        }

        if (tokensOnNewLine.Count == 0)
        {
            return node;
        }

        return node.ReplaceTokens(tokensOnNewLine,
                                  (original, rewritten) => AdjustLeadingWhitespace(rewritten, columnOffset, afterEndOfLine[original]));
    }

    #endregion // Methods

    #region Private methods

    /// <summary>
    /// Determines whether a trivia is a single-line or multi-line comment
    /// </summary>
    /// <param name="trivia">The trivia to check</param>
    /// <returns><see langword="true"/> if the trivia is a comment; otherwise, <see langword="false"/></returns>
    private static bool IsCommentTrivia(SyntaxTrivia trivia)
    {
        return trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
               || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia);
    }

    /// <summary>
    /// Determines whether comment text contains a generated-file marker
    /// </summary>
    /// <param name="commentText">The comment text to inspect</param>
    /// <returns><see langword="true"/> if a marker is present; otherwise, <see langword="false"/></returns>
    private static bool ContainsAutoGeneratedMarker(string commentText)
    {
        return commentText.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0
               || commentText.IndexOf("<autogenerated", StringComparison.OrdinalIgnoreCase) >= 0;
    }

    /// <summary>
    /// Determines whether the given ancestor node is an indenting construct
    /// that contains the specified span position within its braces
    /// </summary>
    /// <param name="node">The ancestor node to check</param>
    /// <param name="spanStart">The span start position of the node being checked</param>
    /// <returns><c>true</c> if the ancestor increases indentation; otherwise, <c>false</c></returns>
    private static bool IsIndentingAncestor(SyntaxNode node, int spanStart)
    {
        switch (node)
        {
            case BlockSyntax block:
                return IsBetweenBraces(spanStart, block.OpenBraceToken, block.CloseBraceToken);

            case TypeDeclarationSyntax typeDecl:
                return IsBetweenBraces(spanStart, typeDecl.OpenBraceToken, typeDecl.CloseBraceToken);

            case NamespaceDeclarationSyntax nsDecl:
                return IsBetweenBraces(spanStart, nsDecl.OpenBraceToken, nsDecl.CloseBraceToken);

            case EnumDeclarationSyntax enumDecl:
                return IsBetweenBraces(spanStart, enumDecl.OpenBraceToken, enumDecl.CloseBraceToken);

            case SwitchStatementSyntax switchStmt:
                return IsBetweenBraces(spanStart, switchStmt.OpenBraceToken, switchStmt.CloseBraceToken);

            case AccessorListSyntax accessorList:
                return IsBetweenBraces(spanStart, accessorList.OpenBraceToken, accessorList.CloseBraceToken);

            case InitializerExpressionSyntax initializer:
                return IsBetweenBraces(spanStart, initializer.OpenBraceToken, initializer.CloseBraceToken);

            case AnonymousObjectCreationExpressionSyntax anon:
                return IsBetweenBraces(spanStart, anon.OpenBraceToken, anon.CloseBraceToken);

            default:
                return false;
        }
    }

    /// <summary>
    /// Determines whether a span position falls between the open and close brace tokens
    /// </summary>
    /// <param name="spanStart">The span start position to check</param>
    /// <param name="openBrace">The open brace token</param>
    /// <param name="closeBrace">The close brace token</param>
    /// <returns><c>true</c> if the position is between the braces; otherwise, <c>false</c></returns>
    private static bool IsBetweenBraces(int spanStart, SyntaxToken openBrace, SyntaxToken closeBrace)
    {
        if (openBrace.IsMissing || closeBrace.IsMissing)
        {
            return false;
        }

        return spanStart > openBrace.SpanStart && spanStart < closeBrace.SpanStart;
    }

    /// <summary>
    /// Determines whether a token starts on a new line by checking for
    /// end-of-line trivia in the token's leading trivia or the previous token's trailing trivia
    /// </summary>
    /// <param name="token">The token to check</param>
    /// <returns><see langword="true"/> if the token starts on a new line; otherwise, <see langword="false"/></returns>
    private static bool StartsOnNewLine(SyntaxToken token)
    {
        return token.LeadingTrivia.Any(static trivia => trivia.IsKind(SyntaxKind.EndOfLineTrivia))
               || IsAfterEndOfLine(token);
    }

    /// <summary>
    /// Determines whether the previous token's trailing trivia ends with an end-of-line trivia
    /// </summary>
    /// <param name="token">The token to check</param>
    /// <returns><see langword="true"/> if the previous token's trailing trivia ends with EOL; otherwise, <see langword="false"/></returns>
    private static bool IsAfterEndOfLine(SyntaxToken token)
    {
        var prevToken = token.GetPreviousToken();

        if (prevToken == default)
        {
            return false;
        }

        var trailing = prevToken.TrailingTrivia;

        return trailing.Count > 0 && trailing.Last().IsKind(SyntaxKind.EndOfLineTrivia);
    }

    /// <summary>
    /// Adjusts the leading whitespace trivia of a token by the given column offset.
    /// Only whitespace trivia that appears at the beginning of a line is adjusted
    /// </summary>
    /// <param name="token">The token whose leading whitespace to adjust</param>
    /// <param name="columnOffset">The number of columns to shift (positive = right, negative = left)</param>
    /// <param name="previousEndsWithEndOfLine">Whether the previous token's trailing trivia ends with an end-of-line</param>
    /// <returns>A new token with adjusted leading whitespace</returns>
    private static SyntaxToken AdjustLeadingWhitespace(SyntaxToken token, int columnOffset, bool previousEndsWithEndOfLine)
    {
        var leadingTrivia = token.LeadingTrivia;
        var newTrivia = new List<SyntaxTrivia>(leadingTrivia.Count);
        var atLineStart = previousEndsWithEndOfLine;

        foreach (var trivia in leadingTrivia)
        {
            if (atLineStart && trivia.IsKind(SyntaxKind.WhitespaceTrivia))
            {
                var currentWidth = trivia.Span.Length;
                var newWidth = Math.Max(0, currentWidth + columnOffset);

                newTrivia.Add(SyntaxFactory.Whitespace(new string(' ', newWidth)));
                atLineStart = false;
            }
            else
            {
                newTrivia.Add(trivia);
                atLineStart = trivia.IsKind(SyntaxKind.EndOfLineTrivia);
            }
        }

        return token.WithLeadingTrivia(newTrivia);
    }

    #endregion // Private methods
}