using System.Threading.Tasks;

using Microsoft.CodeAnalysis;

using Reihitsu.Formatter.Pipeline;

namespace Reihitsu.Formatter;

/// <summary>
/// Reihitsu code formatter
/// </summary>
public static class ReihitsuFormatter
{
    #region Methods

    /// <summary>
    /// Formats an entire document by applying all formatting rules
    /// </summary>
    /// <param name="document">The Roslyn Document to format</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>A new Document with formatting applied</returns>
    public static async Task<Document> FormatDocumentAsync(Document document, CancellationToken cancellationToken = default)
    {
        var syntaxTree = await document.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);

        if (syntaxTree == null)
        {
            return document;
        }

        var root = await syntaxTree.GetRootAsync(cancellationToken).ConfigureAwait(false);

        if (ReihitsuFormatterHelpers.HasSyntaxErrors(syntaxTree))
        {
            return document;
        }

        if (ReihitsuFormatterHelpers.IsAutoGeneratedSource(root))
        {
            return document;
        }

        var endOfLine = ReihitsuFormatterHelpers.DetectEndOfLine(root);
        var context = new FormattingContext(endOfLine);
        var formattedRoot = FormattingPipeline.Execute(root, context, cancellationToken);

        return document.WithSyntaxRoot(formattedRoot);
    }

    /// <summary>
    /// Formats a syntax tree by applying all formatting rules.
    /// Use this overload when no Workspace/Document context is available
    /// </summary>
    /// <param name="syntaxTree">The syntax tree to format</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>A new SyntaxTree with formatting applied</returns>
    public static SyntaxTree FormatSyntaxTree(SyntaxTree syntaxTree, CancellationToken cancellationToken = default)
    {
        if (ReihitsuFormatterHelpers.HasSyntaxErrors(syntaxTree))
        {
            return syntaxTree;
        }

        var root = syntaxTree.GetRoot(cancellationToken);

        if (ReihitsuFormatterHelpers.IsAutoGeneratedSource(root))
        {
            return syntaxTree;
        }

        var endOfLine = ReihitsuFormatterHelpers.DetectEndOfLine(root);
        var context = new FormattingContext(endOfLine);
        var formattedRoot = FormattingPipeline.Execute(root, context, cancellationToken);

        return syntaxTree.WithRootAndOptions(formattedRoot, syntaxTree.Options);
    }

    /// <summary>
    /// Formats a specific syntax node and its descendants.
    /// Useful for code fix providers that need to format only a
    /// newly generated or modified node rather than the full document
    /// </summary>
    /// <param name="node">The syntax node to format</param>
    /// <param name="indentLevel">
    /// The indentation level of the node within its containing document.
    /// Required for newly generated nodes that are not yet inserted into a tree,
    /// where the indentation level cannot be inferred from position
    /// </param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>A new SyntaxNode with formatting applied</returns>
    /// <remarks>
    /// Unlike the document- and tree-level entry points, this overload intentionally omits the
    /// syntax-error and auto-generated guards. It operates on a caller-supplied node — typically a
    /// freshly generated or detached subtree produced by a code fix — that has no file header to
    /// inspect and is not expected to carry whole-file error diagnostics. Callers are responsible for
    /// passing a node that is safe to format
    /// </remarks>
    public static SyntaxNode FormatNode(SyntaxNode node, int indentLevel = -1, CancellationToken cancellationToken = default)
    {
        var endOfLine = ReihitsuFormatterHelpers.DetectEndOfLine(node);
        var baseIndentLevel = indentLevel >= 0 ? indentLevel : ReihitsuFormatterHelpers.ComputeBaseIndentLevel(node);
        var context = new FormattingContext(endOfLine, baseIndentLevel);

        return FormattingPipeline.Execute(node, context, cancellationToken);
    }

    /// <summary>
    /// Formats a specific syntax node using document-derived indentation and line-ending context.
    /// Only the targeted node is rewritten back into the document; callers that intend document-wide
    /// formatting should use <see cref="FormatDocumentAsync(Document, CancellationToken)"/> instead
    /// </summary>
    /// <param name="document">The Roslyn Document containing the target node</param>
    /// <param name="targetNode">The syntax node to format. Must belong to the document's syntax tree</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>A new Document with only the targeted node formatted</returns>
    public static async Task<Document> FormatNodeInDocumentAsync(Document document, SyntaxNode targetNode, CancellationToken cancellationToken = default)
    {
        var syntaxTree = await document.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);

        if (syntaxTree == null)
        {
            return document;
        }

        var root = await syntaxTree.GetRootAsync(cancellationToken).ConfigureAwait(false);

        if (ReihitsuFormatterHelpers.HasSyntaxErrors(syntaxTree))
        {
            return document;
        }

        if (ReihitsuFormatterHelpers.IsAutoGeneratedSource(root))
        {
            return document;
        }

        var originalFirstToken = targetNode.GetFirstToken();
        var originalColumn = ReihitsuFormatterHelpers.ComputeTokenColumn(originalFirstToken, root);
        var endOfLine = ReihitsuFormatterHelpers.DetectEndOfLine(root);
        var baseIndentLevel = ReihitsuFormatterHelpers.ComputeBaseIndentLevel(targetNode);
        var context = new FormattingContext(endOfLine, baseIndentLevel);
        var formattedTarget = FormattingPipeline.Execute(targetNode, context, cancellationToken);
        var formattedColumn = ReihitsuFormatterHelpers.ComputeTokenColumn(formattedTarget.GetFirstToken(), formattedTarget);
        var columnOffset = originalColumn - formattedColumn;

        if (columnOffset != 0)
        {
            formattedTarget = ReihitsuFormatterHelpers.AdjustNodeIndentation(formattedTarget, columnOffset);
        }

        if (targetNode.Parent == root || ReihitsuFormatterHelpers.StartsOnNewLine(originalFirstToken) == false)
        {
            var formattedFirstToken = formattedTarget.GetFirstToken();
            formattedTarget = formattedTarget.ReplaceToken(formattedFirstToken, formattedFirstToken.WithLeadingTrivia(originalFirstToken.LeadingTrivia));
        }

        if (targetNode == root)
        {
            return document.WithSyntaxRoot(formattedTarget);
        }

        var originalLastToken = targetNode.GetLastToken();
        var formattedLastToken = formattedTarget.GetLastToken();
        formattedTarget = formattedTarget.ReplaceToken(formattedLastToken, formattedLastToken.WithTrailingTrivia(originalLastToken.TrailingTrivia));

        return document.WithSyntaxRoot(root.ReplaceNode(targetNode, formattedTarget));
    }

    /// <summary>
    /// Formats a target node using a containing node for positional context, then rewrites only the
    /// target node back into the document. This is useful when the target starts in the middle of a
    /// line and formatter phases need the preceding owner tokens to compute absolute columns
    /// </summary>
    /// <param name="document">The Roslyn Document containing both nodes</param>
    /// <param name="targetNode">The syntax node whose formatted result should be applied</param>
    /// <param name="contextNode">A containing syntax node used while formatting the target</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>A new Document with only the targeted node formatted</returns>
    public static async Task<Document> FormatNodeInDocumentWithContextAsync(Document document,
                                                                            SyntaxNode targetNode,
                                                                            SyntaxNode contextNode,
                                                                            CancellationToken cancellationToken = default)
    {
        if (targetNode == contextNode)
        {
            return await FormatNodeInDocumentAsync(document, targetNode, cancellationToken).ConfigureAwait(false);
        }

        var syntaxTree = await document.GetSyntaxTreeAsync(cancellationToken).ConfigureAwait(false);

        if (syntaxTree == null
            || targetNode.SyntaxTree != syntaxTree
            || contextNode.SyntaxTree != syntaxTree
            || contextNode.FullSpan.Contains(targetNode.FullSpan) == false)
        {
            return document;
        }

        var root = await syntaxTree.GetRootAsync(cancellationToken).ConfigureAwait(false);

        if (ReihitsuFormatterHelpers.HasSyntaxErrors(syntaxTree)
            || ReihitsuFormatterHelpers.IsAutoGeneratedSource(root))
        {
            return document;
        }

        var originalContextFirstToken = contextNode.GetFirstToken();
        var originalColumn = ReihitsuFormatterHelpers.ComputeTokenColumn(originalContextFirstToken, root);
        var endOfLine = ReihitsuFormatterHelpers.DetectEndOfLine(root);
        var baseIndentLevel = ReihitsuFormatterHelpers.ComputeBaseIndentLevel(contextNode);
        var context = new FormattingContext(endOfLine, baseIndentLevel);
        var targetTokenAnnotation = new SyntaxAnnotation();
        var originalFirstToken = targetNode.GetFirstToken();
        var annotatedTarget = targetNode.ReplaceToken(originalFirstToken,
                                                      originalFirstToken.WithAdditionalAnnotations(targetTokenAnnotation));
        var annotatedContext = contextNode.ReplaceNode(targetNode, annotatedTarget);
        var formattedContext = FormattingPipeline.Execute(annotatedContext, context, cancellationToken);
        var formattedColumn = ReihitsuFormatterHelpers.ComputeTokenColumn(formattedContext.GetFirstToken(), formattedContext);
        var columnOffset = originalColumn - formattedColumn;

        if (columnOffset != 0)
        {
            formattedContext = ReihitsuFormatterHelpers.AdjustNodeIndentation(formattedContext, columnOffset);
        }

        var formattedTarget = FindCorrespondingNode(targetNode, formattedContext, targetTokenAnnotation);

        if (formattedTarget == null)
        {
            return document;
        }

        var formattedFirstToken = formattedTarget.GetFirstToken();
        var updatedFirstToken = formattedFirstToken.WithLeadingTrivia(originalFirstToken.LeadingTrivia)
                                                   .WithoutAnnotations(targetTokenAnnotation);

        formattedTarget = formattedTarget.ReplaceToken(formattedFirstToken, updatedFirstToken);

        var originalLastToken = targetNode.GetLastToken();
        var formattedLastToken = formattedTarget.GetLastToken();
        formattedTarget = formattedTarget.ReplaceToken(formattedLastToken, formattedLastToken.WithTrailingTrivia(originalLastToken.TrailingTrivia));

        return document.WithSyntaxRoot(root.ReplaceNode(targetNode, formattedTarget));
    }

    /// <summary>
    /// Finds a node in a formatted context by following a marked token through the target's internal ancestor path
    /// </summary>
    /// <param name="targetNode">The original target node</param>
    /// <param name="formattedContext">The formatted containing node</param>
    /// <param name="targetTokenAnnotation">The annotation attached to the target's first token</param>
    /// <returns>The corresponding formatted node, or <see langword="null"/> when the marker or structure changed</returns>
    private static SyntaxNode FindCorrespondingNode(SyntaxNode targetNode,
                                                    SyntaxNode formattedContext,
                                                    SyntaxAnnotation targetTokenAnnotation)
    {
        var originalTokenParent = targetNode.GetFirstToken().Parent;

        if (originalTokenParent == null)
        {
            return null;
        }

        var ancestorKinds = new System.Collections.Generic.List<int>();
        var current = originalTokenParent;

        while (true)
        {
            ancestorKinds.Add(current.RawKind);

            if (current == targetNode)
            {
                break;
            }

            current = current.Parent;

            if (current == null)
            {
                return null;
            }
        }

        var annotatedTokens = formattedContext.GetAnnotatedTokens(targetTokenAnnotation)
                                              .Take(2)
                                              .ToArray();

        if (annotatedTokens.Length != 1)
        {
            return null;
        }

        current = annotatedTokens[0].Parent;

        for (var index = 0; index < ancestorKinds.Count; index++)
        {
            var ancestorKind = ancestorKinds[index];

            if (current == null || current.RawKind != ancestorKind)
            {
                return null;
            }

            if (index == ancestorKinds.Count - 1)
            {
                return current;
            }

            current = current.Parent;
        }

        return null;
    }

    #endregion // Methods
}