using System.Collections.Generic;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using Reihitsu.Core;

namespace Reihitsu.Formatter;

/// <summary>
/// Helper methods for the <see cref="ReihitsuFormatter"/> class
/// </summary>
internal static class ReihitsuFormatterHelpers
{
    #region Methods

    /// <summary>
    /// Detects the predominant end-of-line sequence in the syntax node.
    /// Falls back to <see cref="Environment.NewLine"/> if no end-of-line trivia is found
    /// </summary>
    /// <param name="node">The syntax node to analyze</param>
    /// <returns>The detected end-of-line sequence</returns>
    internal static string DetectEndOfLine(SyntaxNode node)
    {
        return LineEndingUtilities.DetectEndOfLine(node);
    }

    /// <summary>
    /// Checks whether the syntax tree contains any syntax errors.
    /// Files with syntax errors are skipped by the formatter
    /// </summary>
    /// <param name="syntaxTree">The syntax tree to check</param>
    /// <returns><see langword="true"/> if the tree has error-level diagnostics; otherwise, <see langword="false"/></returns>
    internal static bool HasSyntaxErrors(SyntaxTree syntaxTree)
    {
        return syntaxTree.GetDiagnostics()
                         .Any(diagnostic => diagnostic.Severity == DiagnosticSeverity.Error);
    }

    /// <summary>
    /// Checks whether the source file is marked as auto-generated.
    /// Only the file header — the leading trivia of the first token — is inspected, so a
    /// comment that merely mentions the marker elsewhere in the file does not disable formatting.
    /// Supports both single-line and multi-line comments containing
    /// the &lt;auto-generated /&gt; marker
    /// </summary>
    /// <param name="root">The syntax root to inspect</param>
    /// <returns><see langword="true"/> if an auto-generated marker is present in the header; otherwise, <see langword="false"/></returns>
    internal static bool IsAutoGeneratedSource(SyntaxNode root)
    {
        var headerTrivia = root.GetFirstToken(includeZeroWidth: true).LeadingTrivia;

        foreach (var trivia in headerTrivia)
        {
            if (IsCommentTrivia(trivia) == false)
            {
                continue;
            }

            if (ContainsAutoGeneratedMarker(trivia.ToString()))
            {
                return true;
            }
        }

        return false;
    }

    /// <summary>
    /// Computes the base indentation level of a node from its position in the syntax tree.
    /// Walks the parent chain and counts indenting constructs (types, namespaces, blocks, etc.)
    /// </summary>
    /// <param name="node">The node whose base indentation level to compute</param>
    /// <returns>The number of indenting ancestor constructs</returns>
    internal static int ComputeBaseIndentLevel(SyntaxNode node)
    {
        return SyntaxIndentationUtilities.ComputeBaseIndentLevel(node);
    }

    /// <summary>
    /// Computes the zero-based column position of a token within a syntax root
    /// by scanning backwards from the token's start position to the beginning of the line
    /// </summary>
    /// <param name="token">The token whose column to compute</param>
    /// <param name="root">The syntax root containing the token</param>
    /// <returns>The zero-based column position of the token</returns>
    internal static int ComputeTokenColumn(SyntaxToken token, SyntaxNode root)
    {
        // When the token belongs to a syntax tree, reuse the tree's cached line table instead of
        // materializing the whole document text on every call.
        var syntaxTree = token.SyntaxTree;

        if (syntaxTree != null)
        {
            return syntaxTree.GetLineSpan(token.Span).StartLinePosition.Character;
        }

        var fullText = root.ToFullString();
        var position = token.SpanStart;
        var lineStart = position;

        while (lineStart > 0 && fullText[lineStart - 1] != '\n')
        {
            lineStart--;
        }

        return position - lineStart;
    }

    /// <summary>
    /// Adjusts the indentation of all tokens within a node that start on a new line
    /// by the given column offset
    /// </summary>
    /// <param name="node">The syntax node whose indentation to adjust</param>
    /// <param name="columnOffset">The number of columns to shift (positive = right, negative = left)</param>
    /// <returns>A new syntax node with adjusted indentation</returns>
    internal static SyntaxNode AdjustNodeIndentation(SyntaxNode node, int columnOffset)
    {
        var firstToken = node.GetFirstToken();
        var tokensToAdjust = new List<SyntaxToken>();
        var afterEndOfLine = new Dictionary<SyntaxToken, bool>();

        foreach (var token in node.DescendantTokens())
        {
            var isFirstToken = token == firstToken;

            if (isFirstToken == false && StartsOnNewLine(token) == false)
            {
                continue;
            }

            tokensToAdjust.Add(token);
            afterEndOfLine[token] = isFirstToken || IsAfterEndOfLine(token);
        }

        if (tokensToAdjust.Count == 0)
        {
            return node;
        }

        return node.ReplaceTokens(tokensToAdjust,
                                  (original, rewritten) => AdjustLeadingWhitespace(rewritten, columnOffset, afterEndOfLine[original]));
    }

    /// <summary>
    /// Determines whether the token has a comment directly above its line
    /// </summary>
    /// <param name="token">The token to inspect</param>
    /// <returns><see langword="true"/> if a comment is directly above the token; otherwise, <see langword="false"/></returns>
    internal static bool HasCommentDirectlyAbove(SyntaxToken token)
    {
        return SyntaxTriviaUtilities.HasCommentDirectlyAbove(token);
    }

    /// <summary>
    /// Determines whether a trivia is a comment
    /// </summary>
    /// <param name="trivia">The trivia to check</param>
    /// <returns><see langword="true"/> if the trivia is a comment; otherwise, <see langword="false"/></returns>
    internal static bool IsCommentTrivia(SyntaxTrivia trivia)
    {
        return SyntaxTriviaUtilities.IsCommentTrivia(trivia);
    }

    /// <summary>
    /// Determines whether a trivia is a preprocessor directive or disabled (conditionally compiled out) text
    /// </summary>
    /// <param name="trivia">The trivia to check</param>
    /// <returns><see langword="true"/> if the trivia is a directive or disabled text; otherwise, <see langword="false"/></returns>
    internal static bool IsDirectiveOrDisabledTextTrivia(SyntaxTrivia trivia)
    {
        return SyntaxTriviaUtilities.IsDirectiveOrDisabledTextTrivia(trivia);
    }

    /// <summary>
    /// Determines whether a token starts on a new line by checking for
    /// end-of-line trivia in the token's leading trivia or the previous token's trailing trivia
    /// </summary>
    /// <param name="token">The token to check</param>
    /// <returns><see langword="true"/> if the token starts on a new line; otherwise, <see langword="false"/></returns>
    internal static bool StartsOnNewLine(SyntaxToken token)
    {
        return token.LeadingTrivia.Any(static trivia => trivia.IsKind(SyntaxKind.EndOfLineTrivia))
               || IsAfterEndOfLine(token);
    }

    #endregion // Methods

    #region Private methods

    /// <summary>
    /// Determines whether comment text contains a generated-file marker
    /// </summary>
    /// <param name="commentText">The comment text to inspect</param>
    /// <returns><see langword="true"/> if a marker is present; otherwise, <see langword="false"/></returns>
    private static bool ContainsAutoGeneratedMarker(string commentText)
    {
        return commentText.IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0
               || commentText.IndexOf("<autogenerated", StringComparison.OrdinalIgnoreCase) >= 0;
    }

    /// <summary>
    /// Determines whether the previous token's trailing trivia ends with an end-of-line trivia
    /// </summary>
    /// <param name="token">The token to check</param>
    /// <returns><see langword="true"/> if the previous token's trailing trivia ends with EOL; otherwise, <see langword="false"/></returns>
    private static bool IsAfterEndOfLine(SyntaxToken token)
    {
        var prevToken = token.GetPreviousToken();

        if (prevToken == default)
        {
            return false;
        }

        var trailing = prevToken.TrailingTrivia;

        return trailing.Count > 0 && trailing.Last().IsKind(SyntaxKind.EndOfLineTrivia);
    }

    /// <summary>
    /// Adjusts the leading whitespace trivia of a token by the given column offset.
    /// Only whitespace trivia that appears at the beginning of a line is adjusted
    /// </summary>
    /// <param name="token">The token whose leading whitespace to adjust</param>
    /// <param name="columnOffset">The number of columns to shift (positive = right, negative = left)</param>
    /// <param name="previousEndsWithEndOfLine">Whether the previous token's trailing trivia ends with an end-of-line</param>
    /// <returns>A new token with adjusted leading whitespace</returns>
    private static SyntaxToken AdjustLeadingWhitespace(SyntaxToken token, int columnOffset, bool previousEndsWithEndOfLine)
    {
        var leadingTrivia = token.LeadingTrivia;
        var newTrivia = new List<SyntaxTrivia>(leadingTrivia.Count);
        var atLineStart = previousEndsWithEndOfLine;

        foreach (var trivia in leadingTrivia)
        {
            if (atLineStart && trivia.IsKind(SyntaxKind.WhitespaceTrivia))
            {
                var currentWidth = trivia.Span.Length;
                var newWidth = Math.Max(0, currentWidth + columnOffset);

                newTrivia.Add(SyntaxFactory.Whitespace(new string(' ', newWidth)));
                atLineStart = false;
            }
            else
            {
                var adjustedTrivia = trivia;

                if (trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia))
                {
                    adjustedTrivia = DocumentationCommentUtilities.ShiftContinuationExteriorMarkers(trivia, columnOffset);
                }

                newTrivia.Add(adjustedTrivia);
                atLineStart = trivia.IsKind(SyntaxKind.EndOfLineTrivia)
                              || trivia.IsKind(SyntaxKind.SingleLineDocumentationCommentTrivia)
                              || (trivia.HasStructure
                                  && trivia.GetStructure() is DirectiveTriviaSyntax);
            }
        }

        return token.WithLeadingTrivia(newTrivia);
    }

    #endregion // Private methods
}