using Microsoft.CodeAnalysis;

using Reihitsu.Cli.Abstractions;

namespace Reihitsu.Cli;

/// <summary>
/// Represents the reusable result of reading, parsing, and classifying a source file
/// </summary>
/// <param name="FileRead">The source content and encoding metadata</param>
/// <param name="SyntaxTree">The parsed syntax tree</param>
/// <param name="IsAutoGenerated">Whether the shared generated-source policy identifies the file as generated</param>
internal readonly record struct FileInspectionResult(FileReadResult FileRead,
                                                     SyntaxTree SyntaxTree,
                                                     bool IsAutoGenerated);