using System.Threading.Tasks;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using Reihitsu.Cli.Abstractions;
using Reihitsu.Formatter.Data;
using Reihitsu.Formatter.Pipeline;
using Reihitsu.Formatter.Utilities;

namespace Reihitsu.Cli.Diagnostics;

/// <summary>
/// Runs the formatter repeatedly while reporting the source changes made by each top-level pipeline phase
/// </summary>
internal static class PipelineTraceCommand
{
    #region Constants

    /// <summary>
    /// Maximum number of formatting passes used when the caller does not provide an override
    /// </summary>
    private const int DefaultPasses = 3;

    #endregion // Constants

    #region Methods

    /// <summary>
    /// Executes the repository-only pipeline trace command
    /// </summary>
    /// <param name="args">Trace command arguments</param>
    /// <param name="output">Standard output writer</param>
    /// <param name="error">Standard error writer</param>
    /// <param name="cancellationToken">Cancellation token</param>
    /// <returns>
    /// Exit code 0 when the input stabilizes or is legitimately skipped, 1 when it still changes after the requested
    /// passes, or 2 when the command cannot run
    /// </returns>
    internal static async Task<int> ExecuteAsync(string[] args,
                                                 TextWriter output,
                                                 TextWriter error,
                                                 CancellationToken cancellationToken = default)
    {
        if (TryParseArguments(args, out var filePath, out var passes, out var showHelp, out var parseError) == false)
        {
            error.WriteLine($"trace: {parseError}");
            PrintUsage(error);

            return ExitCodes.Error;
        }

        if (showHelp)
        {
            PrintUsage(output);

            return ExitCodes.Success;
        }

        try
        {
            var fileSystem = new DefaultFileSystem();
            var fullPath = fileSystem.GetFullPath(filePath);

            if (fileSystem.FileExists(fullPath) == false)
            {
                error.WriteLine(fileSystem.DirectoryExists(fullPath)
                                    ? $"trace: '{filePath}' is a directory; expected one C# file."
                                    : $"trace: file not found: {filePath}");

                return ExitCodes.Error;
            }

            if (GeneratedFileUtilities.IsGeneratedFile(fullPath))
            {
                output.WriteLine($"Skipped (generated): {fullPath}");

                return ExitCodes.Success;
            }

            var fileRead = await fileSystem.ReadFileAsync(fullPath, cancellationToken).ConfigureAwait(false);
            var currentContent = fileRead.Content;
            var displayPath = filePath.Replace('\\', '/');

            output.WriteLine($"Tracing {fullPath} (maximum passes: {passes})");

            for (var pass = 1; pass <= passes; pass++)
            {
                cancellationToken.ThrowIfCancellationRequested();

                var syntaxTree = CSharpSyntaxTree.ParseText(currentContent, path: fullPath, cancellationToken: cancellationToken);

                if (ReihitsuFormatterHelpers.HasSyntaxErrors(syntaxTree))
                {
                    if (pass == 1)
                    {
                        output.WriteLine($"Skipped (syntax errors): {fullPath}");

                        return ExitCodes.Success;
                    }

                    error.WriteLine($"trace: pass {pass} produced syntax-invalid source before the next pass could run.");

                    return ExitCodes.Error;
                }

                var root = syntaxTree.GetRoot(cancellationToken);

                if (ReihitsuFormatterHelpers.IsAutoGeneratedSource(root))
                {
                    if (pass == 1)
                    {
                        output.WriteLine($"Skipped (generated): {fullPath}");

                        return ExitCodes.Success;
                    }

                    error.WriteLine($"trace: pass {pass} produced generated source before the next pass could run.");

                    return ExitCodes.Error;
                }

                output.WriteLine($"Pass {pass}");

                var passInput = currentContent;
                var context = new FormattingContext(ReihitsuFormatterHelpers.DetectEndOfLine(root));
                var changedPhaseCount = 0;
                string activePhase = null;
                SyntaxNode formattedRoot;

                try
                {
                    formattedRoot = FormattingPipeline.Execute(root,
                                                               context,
                                                               (phaseName, phaseInput, phaseOutput) =>
                                                               {
                                                                   activePhase = phaseName;

                                                                   var before = phaseInput.ToFullString();
                                                                   var after = phaseOutput.ToFullString();

                                                                   if (string.Equals(before, after, StringComparison.Ordinal))
                                                                   {
                                                                       return;
                                                                   }

                                                                   changedPhaseCount++;
                                                                   output.WriteLine($"== Pass {pass}: {phaseName} ==");

                                                                   var diff = DiffGenerator.Generate(displayPath, before, after);

                                                                   if (diff.Length > 0)
                                                                   {
                                                                       output.Write(diff);
                                                                   }
                                                                   else
                                                                   {
                                                                       output.WriteLine($"Line endings: {DescribeLineEndings(before)} -> {DescribeLineEndings(after)}");
                                                                   }
                                                               },
                                                               cancellationToken);
                }
                catch (InvalidOperationException exception) when (exception.Message.StartsWith("Formatting phase '", StringComparison.Ordinal))
                {
                    error.WriteLine($"trace: pass {pass}: {exception.Message} {exception.InnerException?.Message}");

                    return ExitCodes.Error;
                }
                catch (Exception exception) when (exception is not OperationCanceledException)
                {
                    var phaseContext = activePhase == null ? string.Empty : $", phase {activePhase}";

                    error.WriteLine($"trace: pass {pass}{phaseContext}: {exception.Message}");

                    return ExitCodes.Error;
                }

                currentContent = formattedRoot.ToFullString();

                if (string.Equals(passInput, currentContent, StringComparison.Ordinal))
                {
                    output.WriteLine($"Stable after pass {pass} ({changedPhaseCount} phase changes observed).");

                    return ExitCodes.Success;
                }

                output.WriteLine($"Pass {pass} changed source in {changedPhaseCount} phase(s).");
            }

            output.WriteLine($"Not stable after {passes} pass(es).");

            return ExitCodes.FormattingNeeded;
        }
        catch (OperationCanceledException)
        {
            error.WriteLine("trace: operation canceled.");

            return ExitCodes.Error;
        }
        catch (Exception exception)
        {
            error.WriteLine($"trace: {exception.Message}");

            return ExitCodes.Error;
        }
    }

    /// <summary>
    /// Describes the ordinary line-ending sequences contained in source text
    /// </summary>
    /// <param name="text">Source text to inspect</param>
    /// <returns>Counts for CRLF, LF, and CR line endings</returns>
    private static string DescribeLineEndings(string text)
    {
        var crlf = 0;
        var lf = 0;
        var cr = 0;

        for (var index = 0; index < text.Length; index++)
        {
            if (text[index] == '\r')
            {
                if (index + 1 < text.Length && text[index + 1] == '\n')
                {
                    crlf++;
                    index++;
                }
                else
                {
                    cr++;
                }
            }
            else if (text[index] == '\n')
            {
                lf++;
            }
        }

        return $"CRLF={crlf}, LF={lf}, CR={cr}";
    }

    /// <summary>
    /// Prints trace command usage
    /// </summary>
    /// <param name="writer">Writer that receives the usage text</param>
    private static void PrintUsage(TextWriter writer)
    {
        writer.WriteLine("usage: trace <file> [--passes <positive-integer>]");
        writer.WriteLine("       trace --help");
    }

    /// <summary>
    /// Parses trace command arguments
    /// </summary>
    /// <param name="args">Arguments to parse</param>
    /// <param name="filePath">The single input file path</param>
    /// <param name="passes">Maximum number of formatting passes</param>
    /// <param name="showHelp">Whether usage should be printed</param>
    /// <param name="error">Argument error when parsing fails</param>
    /// <returns><see langword="true"/> when the arguments are valid; otherwise, <see langword="false"/></returns>
    private static bool TryParseArguments(string[] args,
                                          out string filePath,
                                          out int passes,
                                          out bool showHelp,
                                          out string error)
    {
        filePath = null;
        passes = DefaultPasses;
        showHelp = false;
        error = null;

        var passesSpecified = false;
        var pathsOnly = false;

        for (var argumentIndex = 0; argumentIndex < args.Length; argumentIndex++)
        {
            var argument = args[argumentIndex];

            if (pathsOnly == false && (argument is "--help" or "-h"))
            {
                showHelp = true;

                continue;
            }

            if (pathsOnly == false && argument == "--")
            {
                pathsOnly = true;

                continue;
            }

            if (pathsOnly == false && argument == "--passes")
            {
                if (passesSpecified)
                {
                    error = "--passes may only be specified once.";

                    return false;
                }

                if (argumentIndex + 1 >= args.Length
                    || int.TryParse(args[++argumentIndex], out passes) == false
                    || passes <= 0)
                {
                    error = "--passes requires a positive integer.";

                    return false;
                }

                passesSpecified = true;

                continue;
            }

            if (pathsOnly == false && argument.StartsWith('-'))
            {
                error = $"unknown argument '{argument}'.";

                return false;
            }

            if (filePath != null)
            {
                error = "expected exactly one input file.";

                return false;
            }

            filePath = argument;
        }

        if (showHelp)
        {
            return true;
        }

        if (string.IsNullOrWhiteSpace(filePath))
        {
            error = "expected one input file.";

            return false;
        }

        return true;
    }

    #endregion // Methods
}