using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

using Microsoft.VisualStudio.TestTools.UnitTesting;

using Reihitsu.Cli.Abstractions;
using Reihitsu.Cli.Test.Helpers;

namespace Reihitsu.Cli.Test.Integration;

/// <summary>
/// Integration tests for <see cref="FormatCommandHandler"/> using real file system
/// </summary>
[TestClass]
public class FormatCommandHandlerIntegrationTests
{
    #region Constants

    /// <summary>
    /// Source code that needs formatting (missing blank line before if statement and missing space after if keyword)
    /// </summary>
    private const string ValidInputTestData = """
                                              using System;

                                              namespace TestProject
                                              {
                                                  public class Example
                                                  {
                                                      public void Method()
                                                      {
                                                          var x = 1;
                                                          if(x == 1)
                                                          {
                                                              Console.WriteLine("hello");
                                                          }
                                                      }
                                                  }
                                              }
                                              """;

    /// <summary>
    /// Expected result after formatting the ValidInputTestData
    /// </summary>
    private const string ValidInputResultData = """
                                                using System;

                                                namespace TestProject
                                                {
                                                    public class Example
                                                    {
                                                        public void Method()
                                                        {
                                                            var x = 1;

                                                            if (x == 1)
                                                            {
                                                                Console.WriteLine("hello");
                                                            }
                                                        }
                                                    }
                                                }
                                                """;

    /// <summary>
    /// Source code that represents an auto-generated file (e.g., Designer.cs)
    /// </summary>
    private const string GeneratedFileTestData = """
                                                 //------------------------------------------------------------------------------
                                                 // <auto-generated>
                                                 //     This code was generated by a tool.
                                                 // </auto-generated>
                                                 //------------------------------------------------------------------------------

                                                 namespace TestProject
                                                 {
                                                     internal class Resources
                                                     {
                                                         internal static string MyString
                                                         {
                                                             get { return "hello"; }
                                                         }
                                                     }
                                                 }
                                                 """;

    /// <summary>
    /// Source code that contains an auto-generated marker in a regular .cs file
    /// </summary>
    private const string AutoGeneratedMarkerFileTestData = """
                                                           // <auto-generated />
                                                           using System;
                                                           
                                                           namespace TestProject
                                                           {
                                                               public class Example
                                                               {
                                                                   public void Method()
                                                                   {
                                                                       var x = 1;
                                                                       if(x == 1)
                                                                       {
                                                                           Console.WriteLine("hello");
                                                                       }
                                                                   }
                                                               }
                                                           }
                                                           """;

    /// <summary>
    /// Source code that contains a syntax error
    /// </summary>
    private const string SyntaxErrorTestData = """
                                               using System;

                                               namespace TestProject
                                               {
                                                   public class Broken
                                                   {
                                                       public void Method()
                                                       {
                                                           var x = // missing expression
                                                       }
                                                   }
                                               """;

    /// <summary>
    /// Source code that needs formatting and contains non-ASCII characters (ü and ß) which are encoded as single
    /// bytes when written with a legacy Latin-1/Windows-1252 encoding and are therefore invalid UTF-8
    /// </summary>
    private const string NonUtf8TestData = """
                                           using System;

                                           namespace TestProject
                                           {
                                               public class Example
                                               {
                                                   public void Method()
                                                   {
                                                       var text = "Grüße";
                                                       if(text.Length == 1)
                                                       {
                                                           Console.WriteLine(text);
                                                       }
                                                   }
                                               }
                                           }
                                           """;

    /// <summary>
    /// Marker character in <see cref="InvalidEncodingTestData"/> that <see cref="CreateInvalidEncodingTestData"/>
    /// replaces with an invalid byte sequence
    /// </summary>
    private const char InvalidEncodingMarker = 'Q';

    /// <summary>
    /// Source code that needs formatting and contains a single <see cref="InvalidEncodingMarker"/> character that
    /// gets replaced with an invalid byte sequence (for example an unpaired UTF-16 surrogate) to simulate a
    /// corrupted UTF-16/UTF-32 file
    /// </summary>
    private const string InvalidEncodingTestData = """
                                                   using System;

                                                   namespace TestProject
                                                   {
                                                       public class Example
                                                       {
                                                           public void Method()
                                                           {
                                                               var text = "Qb";
                                                               if(text.Length == 1)
                                                               {
                                                                   Console.WriteLine(text);
                                                               }
                                                           }
                                                       }
                                                   }
                                                   """;

    #endregion // Constants

    #region Properties

    /// <summary>
    /// Test context for the current test
    /// </summary>
    public TestContext TestContext { get; set; }

    #endregion // Properties

    #region Methods

    /// <summary>
    /// Tests that a single unformatted file is formatted correctly on disk
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncFormatsSingleFileOnDisk()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var filePath = tempDir.CreateFile("Test.cs", ValidInputTestData);

            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);

            var actualContent = await File.ReadAllTextAsync(filePath, TestContext.CancellationToken);

            Assert.AreEqual(ValidInputResultData, actualContent);
        }
    }

    /// <summary>
    /// Tests that files in subdirectories are formatted recursively
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncFormatsDirectoryRecursively()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var filePath1 = tempDir.CreateFile("sub1\\file1.cs", ValidInputTestData);
            var filePath2 = tempDir.CreateFile("sub2\\file2.cs", ValidInputTestData);

            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);

            var content1 = await File.ReadAllTextAsync(filePath1, TestContext.CancellationToken);
            var content2 = await File.ReadAllTextAsync(filePath2, TestContext.CancellationToken);

            Assert.AreEqual(ValidInputResultData, content1);
            Assert.AreEqual(ValidInputResultData, content2);
        }
    }

    /// <summary>
    /// Tests that generated files (.Designer.cs) are skipped and not modified
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsGeneratedFilesOnDisk()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var generatedPath = tempDir.CreateFile("Resource.Designer.cs", GeneratedFileTestData);
            var originalContent = GeneratedFileTestData;

            var handler = CreateHandler([tempDir.Path]);

            // Act
            await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            var actualContent = await File.ReadAllTextAsync(generatedPath, TestContext.CancellationToken);

            Assert.AreEqual(originalContent, actualContent);
        }
    }

    /// <summary>
    /// Tests that files marked with an auto-generated comment are not modified even when they do not use generated file name suffixes
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsFilesMarkedWithAutoGeneratedCommentOnDisk()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var generatedPath = tempDir.CreateFile("GeneratedByComment.cs", AutoGeneratedMarkerFileTestData);
            var originalContent = AutoGeneratedMarkerFileTestData;

            var handler = CreateHandler([tempDir.Path]);

            // Act
            await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            var actualContent = await File.ReadAllTextAsync(generatedPath, TestContext.CancellationToken);

            Assert.AreEqual(originalContent, actualContent);
        }
    }

    /// <summary>
    /// Tests that UTF-8 BOM normalization preserves comment-marked generated files byte-for-byte in every command mode
    /// </summary>
    /// <param name="marker">The supported generated-source marker to place in the file header</param>
    /// <param name="mode">The command mode to exercise</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    [DataRow("<auto-generated />", "normal")]
    [DataRow("<auto-generated />", "check")]
    [DataRow("<auto-generated />", "dry-run")]
    [DataRow("<autogenerated />", "normal")]
    [DataRow("<autogenerated />", "check")]
    [DataRow("<autogenerated />", "dry-run")]
    public async Task ExecuteAsyncUtf8BomSkipsCommentMarkedGeneratedFile(string marker, string mode)
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var generatedContent = AutoGeneratedMarkerFileTestData.Replace("<auto-generated />", marker, StringComparison.Ordinal);
            var generatedPath = tempDir.CreateFile("GeneratedByComment.cs", generatedContent);
            var originalBytes = await File.ReadAllBytesAsync(generatedPath, TestContext.CancellationToken);
            var checkOnly = string.Equals(mode, "check", StringComparison.Ordinal);
            var dryRun = string.Equals(mode, "dry-run", StringComparison.Ordinal);
            var handler = CreateHandler([tempDir.Path], checkOnly, dryRun, false, out var console, utf8Bom: true);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);

            var actualBytes = await File.ReadAllBytesAsync(generatedPath, TestContext.CancellationToken);

            Assert.AreSequenceEqual(originalBytes, actualBytes);
            Assert.Contains(line => line == "Skipped 1 generated file(s).", console.StandardOutput);
            Assert.Contains(line => line.Contains("0 of 0 file(s)", StringComparison.Ordinal), console.StandardOutput);
        }
    }

    /// <summary>
    /// Tests that a recursive parent target processes an ordinary sibling without touching or reporting files in
    /// bin/ and obj/ directories
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsBinAndObjDirectories()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var normalPath = tempDir.CreateFile(Path.Combine("src", "Test.cs"), ValidInputTestData);
            var binPath = tempDir.CreateFile(Path.Combine("bin", "Debug", "Test.cs"), ValidInputTestData);
            var objPath = tempDir.CreateFile(Path.Combine("obj", "Debug", "Test.cs"), ValidInputTestData);

            var handler = CreateHandler([tempDir.Path], out var console);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            var normalContent = await File.ReadAllTextAsync(normalPath, TestContext.CancellationToken);
            var binContent = await File.ReadAllTextAsync(binPath, TestContext.CancellationToken);
            var objContent = await File.ReadAllTextAsync(objPath, TestContext.CancellationToken);
            var output = string.Join(Environment.NewLine, console.StandardOutput);

            Assert.AreEqual(ExitCodes.Success, exitCode);
            Assert.AreEqual(ValidInputResultData, normalContent);
            Assert.AreEqual(ValidInputTestData, binContent);
            Assert.AreEqual(ValidInputTestData, objContent);
            Assert.Contains(normalPath, output);
            Assert.DoesNotContain(binPath, output);
            Assert.DoesNotContain(objPath, output);
        }
    }

    /// <summary>
    /// Tests that files with syntax errors are skipped while other files are still processed
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsFilesWithSyntaxErrorsOnDisk()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var validPath = tempDir.CreateFile("Valid.cs", ValidInputTestData);
            var brokenPath = tempDir.CreateFile("Broken.cs", SyntaxErrorTestData);
            var originalBrokenContent = SyntaxErrorTestData;

            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);

            var validContent = await File.ReadAllTextAsync(validPath, TestContext.CancellationToken);
            var brokenContent = await File.ReadAllTextAsync(brokenPath, TestContext.CancellationToken);

            Assert.AreEqual(ValidInputResultData, validContent);
            Assert.AreEqual(originalBrokenContent, brokenContent);
        }
    }

    /// <summary>
    /// Tests that check mode does not modify any files on disk
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncCheckModeDoesNotModifyFiles()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var filePath = tempDir.CreateFile("Test.cs", ValidInputTestData);
            var originalContent = ValidInputTestData;

            var handler = CreateHandler([tempDir.Path], checkOnly: true);

            // Act
            await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            var actualContent = await File.ReadAllTextAsync(filePath, TestContext.CancellationToken);

            Assert.AreEqual(originalContent, actualContent);
        }
    }

    /// <summary>
    /// Tests that dry-run mode does not modify any files on disk
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncDryRunDoesNotModifyFiles()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var filePath = tempDir.CreateFile("Test.cs", ValidInputTestData);
            var originalContent = ValidInputTestData;

            var handler = CreateHandler([tempDir.Path], dryRun: true);

            // Act
            await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            var actualContent = await File.ReadAllTextAsync(filePath, TestContext.CancellationToken);

            Assert.AreEqual(originalContent, actualContent);
        }
    }

    /// <summary>
    /// Tests that check mode returns <see cref="ExitCodes.FormattingNeeded"/> for unformatted files
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncCheckModeReturnCorrectExitCode()
    {
        // Arrange

        using (var tempDir = new TemporaryDirectoryFixture())
        {
            tempDir.CreateFile("Test.cs", ValidInputTestData);

            var handler = CreateHandler([tempDir.Path], checkOnly: true);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.FormattingNeeded, exitCode);
        }
    }

    /// <summary>
    /// Tests that a directory with already-formatted files returns <see cref="ExitCodes.Success"/>
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncFormattedDirectoryReturnsSuccess()
    {
        // Arrange

        using (var tempDir = new TemporaryDirectoryFixture())
        {
            tempDir.CreateFile("Test.cs", ValidInputResultData);

            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);
        }
    }

    /// <summary>
    /// Tests that dry-run mode produces unified diff output containing hunk headers
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncDryRunProducesUnifiedDiffOutput()
    {
        // Arrange

        using (var tempDir = new TemporaryDirectoryFixture())
        {
            tempDir.CreateFile("Test.cs", ValidInputTestData);

            var handler = CreateHandler([tempDir.Path], false, true, false, out var console);

            // Act
            await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            var output = string.Join(Environment.NewLine, console.StandardOutput);

            Assert.Contains("@@", output, "Expected unified diff hunk headers (@@) in dry-run output.");
        }
    }

    /// <summary>
    /// Tests that the summary output shows correct counts for a mix of files
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSummaryCountsAreCorrect()
    {
        // Arrange

        using (var tempDir = new TemporaryDirectoryFixture())
        {
            tempDir.CreateFile("Test.cs", ValidInputTestData);
            tempDir.CreateFile("Resource.Designer.cs", GeneratedFileTestData);
            tempDir.CreateFile("Broken.cs", SyntaxErrorTestData);

            var handler = CreateHandler([tempDir.Path], out var console);

            // Act
            await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            var output = console.StandardOutput;

            Assert.Contains("Formatted 1 of 2 file(s).", output, "Expected correct formatted/total count in summary.");
            Assert.Contains("Skipped 1 generated file(s).", output, "Expected generated file skip count in summary.");
            Assert.Contains("Skipped 1 file(s) with syntax errors.",
                            output,
                            "Expected syntax error skip count in summary.");
        }
    }

    /// <summary>
    /// Tests that an empty directory returns <see cref="ExitCodes.Success"/> and outputs the expected message
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncEmptyDirectoryReturnsSuccess()
    {
        // Arrange

        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var handler = CreateHandler([tempDir.Path], out var console);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);
            Assert.Contains("No .cs files found.", console.StandardOutput, "Expected 'No .cs files found.' message.");
        }
    }

    /// <summary>
    /// Tests that formatting is idempotent — running the formatter twice produces identical results
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncFormattingIsIdempotent()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var filePath = tempDir.CreateFile("Test.cs", ValidInputTestData);

            var handler1 = CreateHandler([tempDir.Path]);

            // Act - first pass
            await handler1.ExecuteAsync(TestContext.CancellationToken);

            var contentAfterFirstPass = await File.ReadAllTextAsync(filePath, TestContext.CancellationToken);

            // Act - second pass
            var handler2 = CreateHandler([tempDir.Path]);
            var exitCode = await handler2.ExecuteAsync(TestContext.CancellationToken);

            var contentAfterSecondPass = await File.ReadAllTextAsync(filePath, TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);
            Assert.AreEqual(contentAfterFirstPass, contentAfterSecondPass);
        }
    }

    /// <summary>
    /// Tests that a UTF-8 file without BOM keeps its encoding after formatting
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncPreservesUtf8WithoutBomEncoding()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var filePath = tempDir.CreateFile("Utf8WithoutBom.cs", ValidInputTestData, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);
            await AssertFileEncodingAndContentAsync(filePath, ValidInputResultData, Array.Empty<byte>(), TestContext.CancellationToken);
        }
    }

    /// <summary>
    /// Tests that a UTF-8 file with BOM keeps its encoding after formatting
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncPreservesUtf8WithBomEncoding()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var utf8WithBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: true);
            var filePath = tempDir.CreateFile("Utf8WithBom.cs", ValidInputTestData, utf8WithBom);
            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);
            await AssertFileEncodingAndContentAsync(filePath, ValidInputResultData, utf8WithBom.GetPreamble(), TestContext.CancellationToken);
        }
    }

    /// <summary>
    /// Tests that a UTF-16 file with BOM keeps its encoding after formatting
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncPreservesUtf16WithBomEncoding()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var utf16WithBom = Encoding.Unicode;
            var filePath = tempDir.CreateFile("Utf16WithBom.cs", ValidInputTestData, utf16WithBom);
            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);
            await AssertFileEncodingAndContentAsync(filePath, ValidInputResultData, utf16WithBom.GetPreamble(), TestContext.CancellationToken);
        }
    }

    /// <summary>
    /// Tests that encoding normalization writes every supported detected input encoding as UTF-8 with a byte order mark
    /// </summary>
    /// <param name="encodingName">The input encoding identifier</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    [DataRow("utf8-no-bom")]
    [DataRow("utf8-bom")]
    [DataRow("utf16-le")]
    [DataRow("utf16-be")]
    [DataRow("utf32-le")]
    [DataRow("utf32-be")]
    public async Task ExecuteAsyncUtf8BomNormalizesSupportedInputEncoding(string encodingName)
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var inputEncoding = CreateEncoding(encodingName);
            var filePath = tempDir.CreateFile($"{encodingName}.cs", ValidInputTestData, inputEncoding);
            var handler = CreateHandler([tempDir.Path], utf8Bom: true);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);

            var utf8WithBom = new UTF8Encoding(encoderShouldEmitUTF8Identifier: true);

            await AssertFileEncodingAndContentAsync(filePath,
                                                    ValidInputResultData,
                                                    utf8WithBom.GetPreamble(),
                                                    TestContext.CancellationToken);
        }
    }

    /// <summary>
    /// Tests that a non-UTF-8 file (legacy Latin-1/Windows-1252) is left byte-for-byte unchanged instead of being
    /// silently corrupted by replacement characters
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsNonUtf8FileWithoutCorruptingContent()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var originalBytes = Encoding.Latin1.GetBytes(NonUtf8TestData);
            var filePath = tempDir.CreateFile("Latin1.cs", originalBytes);
            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);

            var actualBytes = await File.ReadAllBytesAsync(filePath, TestContext.CancellationToken);

            Assert.AreSequenceEqual(originalBytes, actualBytes);
        }
    }

    /// <summary>
    /// Tests that a non-UTF-8 file is reported with a warning that it could not be decoded
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsNonUtf8FileWithWarning()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var originalBytes = Encoding.Latin1.GetBytes(NonUtf8TestData);

            tempDir.CreateFile("Latin1.cs", originalBytes);

            var handler = CreateHandler([tempDir.Path], out var console);

            // Act
            await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.Contains(line => line.Contains("could not decode"), console.ErrorOutput);
        }
    }

    /// <summary>
    /// Tests that a UTF-16 file with an invalid byte sequence (an unpaired surrogate) is left byte-for-byte
    /// unchanged instead of being silently corrupted by replacement characters
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsInvalidUtf16FileWithoutCorruptingContent()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var originalBytes = CreateInvalidEncodingTestData(Encoding.Unicode, [0x00, 0xD8]);
            var filePath = tempDir.CreateFile("InvalidUtf16.cs", originalBytes);
            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);

            var actualBytes = await File.ReadAllBytesAsync(filePath, TestContext.CancellationToken);

            Assert.AreSequenceEqual(originalBytes, actualBytes);
        }
    }

    /// <summary>
    /// Tests that a UTF-16 file with an invalid byte sequence is reported with a warning that it could not be decoded
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsInvalidUtf16FileWithWarning()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var originalBytes = CreateInvalidEncodingTestData(Encoding.Unicode, [0x00, 0xD8]);

            tempDir.CreateFile("InvalidUtf16.cs", originalBytes);

            var handler = CreateHandler([tempDir.Path], out var console);

            // Act
            await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.Contains(line => line.Contains("could not decode"), console.ErrorOutput);
        }
    }

    /// <summary>
    /// Tests that a UTF-32 file with an invalid byte sequence (a surrogate code point, which is not a valid UTF-32
    /// scalar value) is left byte-for-byte unchanged instead of being silently corrupted by replacement characters
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous test operation</returns>
    [TestMethod]
    public async Task ExecuteAsyncSkipsInvalidUtf32FileWithoutCorruptingContent()
    {
        // Arrange
        using (var tempDir = new TemporaryDirectoryFixture())
        {
            var utf32 = new UTF32Encoding(bigEndian: false, byteOrderMark: true);
            var originalBytes = CreateInvalidEncodingTestData(utf32, [0x00, 0xD8, 0x00, 0x00]);
            var filePath = tempDir.CreateFile("InvalidUtf32.cs", originalBytes);
            var handler = CreateHandler([tempDir.Path]);

            // Act
            var exitCode = await handler.ExecuteAsync(TestContext.CancellationToken);

            // Assert
            Assert.AreEqual(ExitCodes.Success, exitCode);

            var actualBytes = await File.ReadAllBytesAsync(filePath, TestContext.CancellationToken);

            Assert.AreSequenceEqual(originalBytes, actualBytes);
        }
    }

    /// <summary>
    /// Creates a <see cref="FormatCommandHandler"/> with real dependencies
    /// </summary>
    /// <param name="paths">The paths to process</param>
    /// <param name="checkOnly">Whether to run in check-only mode</param>
    /// <param name="dryRun">Whether to run in dry-run mode</param>
    /// <param name="verbose">Whether to enable verbose output</param>
    /// <param name="utf8Bom">Whether to normalize processed files to UTF-8 with a byte order mark</param>
    /// <returns>A configured <see cref="FormatCommandHandler"/> instance</returns>
    private static FormatCommandHandler CreateHandler(string[] paths, bool checkOnly = false, bool dryRun = false, bool verbose = false, bool utf8Bom = false)
    {
        return CreateHandler(paths, checkOnly, dryRun, verbose, out _, utf8Bom);
    }

    /// <summary>
    /// Creates a <see cref="FormatCommandHandler"/> with real dependencies and exposes the console output
    /// </summary>
    /// <param name="paths">The paths to process</param>
    /// <param name="console">The captured console output</param>
    /// <returns>A configured <see cref="FormatCommandHandler"/> instance</returns>
    private static FormatCommandHandler CreateHandler(string[] paths, out CapturedConsoleOutput console)
    {
        return CreateHandler(paths, false, false, false, out console);
    }

    /// <summary>
    /// Creates a <see cref="FormatCommandHandler"/> with real dependencies and exposes the console output
    /// </summary>
    /// <param name="paths">The paths to process</param>
    /// <param name="checkOnly">Whether to run in check-only mode</param>
    /// <param name="dryRun">Whether to run in dry-run mode</param>
    /// <param name="verbose">Whether to enable verbose output</param>
    /// <param name="console">The captured console output</param>
    /// <param name="utf8Bom">Whether to normalize processed files to UTF-8 with a byte order mark</param>
    /// <returns>A configured <see cref="FormatCommandHandler"/> instance</returns>
    private static FormatCommandHandler CreateHandler(string[] paths, bool checkOnly, bool dryRun, bool verbose, out CapturedConsoleOutput console, bool utf8Bom = false)
    {
        console = new CapturedConsoleOutput();

        var dependencies = new FormatCommandDependencies(new DefaultFileSystem(),
                                                         console,
                                                         new DefaultConsoleInput(),
                                                         new DefaultSourceFormatter(),
                                                         new DefaultDiffGenerator());

        return new FormatCommandHandler(paths, checkOnly, dryRun, verbose, force: false, utf8Bom, dependencies);
    }

    /// <summary>
    /// Creates one of the encodings recognized by <see cref="DefaultFileSystem"/>
    /// </summary>
    /// <param name="encodingName">The encoding identifier</param>
    /// <returns>The requested encoding, including its byte order mark when applicable</returns>
    private static Encoding CreateEncoding(string encodingName)
    {
        return encodingName switch
               {
                   "utf8-no-bom" => new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
                   "utf8-bom" => new UTF8Encoding(encoderShouldEmitUTF8Identifier: true),
                   "utf16-le" => Encoding.Unicode,
                   "utf16-be" => Encoding.BigEndianUnicode,
                   "utf32-le" => new UTF32Encoding(bigEndian: false, byteOrderMark: true),
                   "utf32-be" => new UTF32Encoding(bigEndian: true, byteOrderMark: true),
                   _ => throw new ArgumentOutOfRangeException(nameof(encodingName), encodingName, "Unsupported test encoding."),
               };
    }

    /// <summary>
    /// Asserts that a file keeps the expected encoding preamble and formatted content
    /// </summary>
    /// <param name="filePath">The formatted file path</param>
    /// <param name="expectedContent">The expected formatted content</param>
    /// <param name="expectedPreamble">The expected encoding preamble</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests</param>
    /// <returns>A <see cref="Task"/> representing the asynchronous assertion operation</returns>
    private static async Task AssertFileEncodingAndContentAsync(string filePath, string expectedContent, byte[] expectedPreamble, CancellationToken cancellationToken)
    {
        var fileSystem = new DefaultFileSystem();
        var fileRead = await fileSystem.ReadFileAsync(filePath, cancellationToken).ConfigureAwait(false);
        var actualPreamble = fileRead.Encoding.GetPreamble();

        Assert.AreSequenceEqual(expectedPreamble, actualPreamble);
        Assert.AreEqual(expectedContent, fileRead.Content);
    }

    /// <summary>
    /// Builds raw file bytes for <see cref="InvalidEncodingTestData"/> encoded with the specified encoding, with the
    /// <see cref="InvalidEncodingMarker"/> character's bytes replaced by an invalid byte sequence of the same length
    /// </summary>
    /// <param name="encoding">The encoding to use, including its BOM preamble</param>
    /// <param name="invalidSequence">The invalid byte sequence to substitute for the marker character</param>
    /// <returns>The raw file bytes</returns>
    private static byte[] CreateInvalidEncodingTestData(Encoding encoding, byte[] invalidSequence)
    {
        var contentBytes = encoding.GetBytes(InvalidEncodingTestData);
        var markerBytes = encoding.GetBytes(InvalidEncodingMarker.ToString());
        var markerIndex = contentBytes.AsSpan().IndexOf(markerBytes);

        Array.Copy(invalidSequence, 0, contentBytes, markerIndex, invalidSequence.Length);

        return [.. encoding.GetPreamble(), .. contentBytes];
    }

    #endregion // Methods
}