//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reihitsu.Cli.Test.Integration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reihitsu.Cli.Test.Integration.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string for a generated (.Designer.cs) file test data.
        /// </summary>
        internal static string GeneratedFileTestData {
            get {
                return ResourceManager.GetString("GeneratedFileTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace TestProject
        ///{
        ///    public class Broken
        ///    {
        ///        public void Method()
        ///        {
        ///            var x = // missing expression
        ///        }
        ///    }.
        /// </summary>
        internal static string SyntaxErrorTestData {
            get {
                return ResourceManager.GetString("SyntaxErrorTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace TestProject
        ///{
        ///    public class Example
        ///    {
        ///        public void Method()
        ///        {
        ///            var x = 1;
        ///
        ///            if (x == 1)
        ///            {
        ///                Console.WriteLine(&quot;hello&quot;);
        ///            }
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string ValidInputResultData {
            get {
                return ResourceManager.GetString("ValidInputResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace TestProject
        ///{
        ///    public class Example
        ///    {
        ///        public void Method()
        ///        {
        ///            var x = 1;
        ///            if(x == 1)
        ///            {
        ///                Console.WriteLine(&quot;hello&quot;);
        ///            }
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string ValidInputTestData {
            get {
                return ResourceManager.GetString("ValidInputTestData", resourceCulture);
            }
        }
    }
}