//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reihitsu.Analyzer.Test.Naming.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reihitsu.Analyzer.Test.Naming.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string RH0202ResultData {
            get {
                return ResourceManager.GetString("RH0202ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class {|#0:testClass|}
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string RH0202TestData {
            get {
                return ResourceManager.GetString("RH0202TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test struct
        ///    /// &lt;/summary&gt;
        ///    public struct TestStruct
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string RH0203ResultData {
            get {
                return ResourceManager.GetString("RH0203ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test struct
        ///    /// &lt;/summary&gt;
        ///    public struct {|#0:testStruct|}
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string RH0203TestData {
            get {
                return ResourceManager.GetString("RH0203TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test enum
        ///    /// &lt;/summary&gt;
        ///    public enum TestEnum
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string RH0204ResultData {
            get {
                return ResourceManager.GetString("RH0204ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test enum
        ///    /// &lt;/summary&gt;
        ///    public enum {|#0:testEnum|}
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string RH0204TestData {
            get {
                return ResourceManager.GetString("RH0204TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test enum
        ///    /// &lt;/summary&gt;
        ///    public enum TestEnum
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Member
        ///        /// &lt;/summary&gt;
        ///        Member
        ///    }
        ///}.
        /// </summary>
        internal static string RH0205ResultData {
            get {
                return ResourceManager.GetString("RH0205ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test enum
        ///    /// &lt;/summary&gt;
        ///    public enum TestEnum
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Member
        ///        /// &lt;/summary&gt;
        ///        {|#0:member|}
        ///    }
        ///}.
        /// </summary>
        internal static string RH0205TestData {
            get {
                return ResourceManager.GetString("RH0205TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test interface
        ///    /// &lt;/summary&gt;
        ///    public interface ITestInterface
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string RH0206ResultData {
            get {
                return ResourceManager.GetString("RH0206ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test interface
        ///    /// &lt;/summary&gt;
        ///    public interface {|#0:itestInterface|}
        ///    {
        ///    }
        ///}.
        /// </summary>
        internal static string RH0206TestData {
            get {
                return ResourceManager.GetString("RH0206TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test event
        ///        /// &lt;/summary&gt;
        ///        public event EventHandler TestEvent;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0207ResultData {
            get {
                return ResourceManager.GetString("RH0207ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test event
        ///        /// &lt;/summary&gt;
        ///        public event EventHandler {|#0:testEvent|};
        ///    }
        ///}.
        /// </summary>
        internal static string RH0207TestData {
            get {
                return ResourceManager.GetString("RH0207TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test delegate
        ///    /// &lt;/summary&gt;
        ///    public delegate void EventHandler(object sender, EventArgs e);
        ///}.
        /// </summary>
        internal static string RH0208ResultData {
            get {
                return ResourceManager.GetString("RH0208ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test delegate
        ///    /// &lt;/summary&gt;
        ///    public delegate void {|#0:eventHandler|}(object sender, EventArgs e);
        ///}.
        /// </summary>
        internal static string RH0208TestData {
            get {
                return ResourceManager.GetString("RH0208TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void Testmethod()
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0209ResultData {
            get {
                return ResourceManager.GetString("RH0209ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void {|#0:testmethod|}()
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0209TestData {
            get {
                return ResourceManager.GetString("RH0209TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void Method()
        ///        {
        ///            void TestLocalFunction()
        ///            {
        ///            }
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0210ResultData {
            get {
                return ResourceManager.GetString("RH0210ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void Method()
        ///        {
        ///            void {|#0:testLocalFunction|}()
        ///            {
        ///            }
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0210TestData {
            get {
                return ResourceManager.GetString("RH0210TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void TestMethod(int parameterName)
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0211ResultData {
            get {
                return ResourceManager.GetString("RH0211ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void TestMethod(int {|#0:ParameterName|})
        ///        {
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0211TestData {
            get {
                return ResourceManager.GetString("RH0211TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test private field
        ///        /// &lt;/summary&gt;
        ///        private int _testField;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0212ResultData {
            get {
                return ResourceManager.GetString("RH0212ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test private field
        ///        /// &lt;/summary&gt;
        ///        private int {|#0:TestField|};
        ///    }
        ///}.
        /// </summary>
        internal static string RH0212TestData {
            get {
                return ResourceManager.GetString("RH0212TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test field
        ///        /// &lt;/summary&gt;
        ///        protected int _testField;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0213ResultData {
            get {
                return ResourceManager.GetString("RH0213ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test field
        ///        /// &lt;/summary&gt;
        ///        protected int {|#0:TestField|};
        ///    }
        ///}.
        /// </summary>
        internal static string RH0213TestData {
            get {
                return ResourceManager.GetString("RH0213TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test field
        ///        /// &lt;/summary&gt;
        ///        internal int TestField;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0214ResultData {
            get {
                return ResourceManager.GetString("RH0214ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test field
        ///        /// &lt;/summary&gt;
        ///        internal int {|#0:testField|};
        ///    }
        ///}.
        /// </summary>
        internal static string RH0214TestData {
            get {
                return ResourceManager.GetString("RH0214TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test field
        ///        /// &lt;/summary&gt;
        ///        public int TestField;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0215ResultData {
            get {
                return ResourceManager.GetString("RH0215ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test field
        ///        /// &lt;/summary&gt;
        ///        public int {|#0:testField|};
        ///    }
        ///}.
        /// </summary>
        internal static string RH0215TestData {
            get {
                return ResourceManager.GetString("RH0215TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test field
        ///        /// &lt;/summary&gt;
        ///        private const int TestField = 42;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0216ResultData {
            get {
                return ResourceManager.GetString("RH0216ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test field
        ///        /// &lt;/summary&gt;
        ///        private const int {|#0:testField|} = 42;
        ///    }
        ///}.
        /// </summary>
        internal static string RH0216TestData {
            get {
                return ResourceManager.GetString("RH0216TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test property
        ///        /// &lt;/summary&gt;
        ///        private int Property { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0217ResultData {
            get {
                return ResourceManager.GetString("RH0217ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test property
        ///        /// &lt;/summary&gt;
        ///        private int {|#0:property|} { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0217TestData {
            get {
                return ResourceManager.GetString("RH0217TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test property
        ///        /// &lt;/summary&gt;
        ///        protected int Property { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0218ResultData {
            get {
                return ResourceManager.GetString("RH0218ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test property
        ///        /// &lt;/summary&gt;
        ///        protected int {|#0:property|} { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0218TestData {
            get {
                return ResourceManager.GetString("RH0218TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test property
        ///        /// &lt;/summary&gt;
        ///        internal int Property { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0219ResultData {
            get {
                return ResourceManager.GetString("RH0219ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test property
        ///        /// &lt;/summary&gt;
        ///        internal int {|#0:property|} { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0219TestData {
            get {
                return ResourceManager.GetString("RH0219TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test property
        ///        /// &lt;/summary&gt;
        ///        public int Property { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0220ResultData {
            get {
                return ResourceManager.GetString("RH0220ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test property
        ///        /// &lt;/summary&gt;
        ///        public int {|#0:property|} { get; set; }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0220TestData {
            get {
                return ResourceManager.GetString("RH0220TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void TestMethod()
        ///        {
        ///            int localVariable = 42;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0221ResultData {
            get {
                return ResourceManager.GetString("RH0221ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void TestMethod()
        ///        {
        ///            int {|#0:LocalVariable|} = 42;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0221TestData {
            get {
                return ResourceManager.GetString("RH0221TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public (int FirstElement, int SecondElement) TestMethod()
        ///        {
        ///            return default;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0222ResultData {
            get {
                return ResourceManager.GetString("RH0222ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public (int {|#0:firstElement|}, int SecondElement) TestMethod()
        ///        {
        ///            return default;
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0222TestData {
            get {
                return ResourceManager.GetString("RH0222TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void TestMethod()
        ///        {
        ///            var (firstVariable, secondVariable) = (1, 2);
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0223ResultData {
            get {
                return ResourceManager.GetString("RH0223ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void TestMethod()
        ///        {
        ///            var ({|#0:FirstVariable|}, secondVariable) = (1, 2);
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0223TestData {
            get {
                return ResourceManager.GetString("RH0223TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void TestMethod()
        ///        {
        ///            var tuple = (FirstElement: 1, SecondElement: 2);
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0224ResultData {
            get {
                return ResourceManager.GetString("RH0224ResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace Reihitsu.Analyzer.Test.Naming.Resources
        ///{
        ///    /// &lt;summary&gt;
        ///    /// Test class
        ///    /// &lt;/summary&gt;
        ///    public class TestClass
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// Test method
        ///        /// &lt;/summary&gt;
        ///        public void TestMethod()
        ///        {
        ///            var tuple = ({|#0:firstElement|}: 1, SecondElement: 2);
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string RH0224TestData {
            get {
                return ResourceManager.GetString("RH0224TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace {|#0:reihitsu|}.Analyzer.Test.{|#1:naming|}.{|#2:resources|};.
        /// </summary>
        internal static string RH0225TestData {
            get {
                return ResourceManager.GetString("RH0225TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace {|#0:reihitsu|}.Analyzer.Test.{|#1:naming|}.{|#2:resources|}
        ///{
        ///}.
        /// </summary>
        internal static string RH0226TestData {
            get {
                return ResourceManager.GetString("RH0226TestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///
        ///namespace TestNameSpace
        ///{
        ///}.
        /// </summary>
        internal static string RH0227TestData {
            get {
                return ResourceManager.GetString("RH0227TestData", resourceCulture);
            }
        }
    }
}
