//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reihitsu.Formatter.Test.Integration.Rules.BlankLines.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reihitsu.Formatter.Test.Integration.Rules.BlankLines.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class BlankLineAfterStatementTestData
        ///{
        ///    public void SwitchWithBreakFollowedByCase()
        ///    {
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                System.Console.WriteLine();
        ///
        ///                break;
        ///
        ///            case 2:
        ///                System.Console.WriteLine();
        ///
        ///                break;
        ///
        ///            default:
        ///                break;
        ///        }
        ///    }
        ///
        ///    public void BreakInLoopFollowedByStatement()
        ///    {
        ///        for (var i = 0; i &lt; 10; i++)
        ///        {
        ///            break;
        ///
        ///            var x = 1;
        ///        }
        ///    }
        ///
        ///    // --- Cases that should NOT be  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlankLineAfterStatementResultData {
            get {
                return ResourceManager.GetString("BlankLineAfterStatementResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class BlankLineAfterStatementTestData
        ///{
        ///    public void SwitchWithBreakFollowedByCase()
        ///    {
        ///        switch (1)
        ///        {
        ///            case 1:
        ///                System.Console.WriteLine();
        ///                break;
        ///            case 2:
        ///                System.Console.WriteLine();
        ///                break;
        ///            default:
        ///                break;
        ///        }
        ///    }
        ///
        ///    public void BreakInLoopFollowedByStatement()
        ///    {
        ///        for (var i = 0; i &lt; 10; i++)
        ///        {
        ///            break;
        ///            var x = 1;
        ///        }
        ///    }
        ///
        ///    // --- Cases that should NOT be modif [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlankLineAfterStatementTestData {
            get {
                return ResourceManager.GetString("BlankLineAfterStatementTestData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class BlankLineBeforeStatementTestData
        ///{
        ///    public void TryStatement()
        ///    {
        ///        var x = 1;
        ///
        ///        try
        ///        {
        ///        }
        ///        catch
        ///        {
        ///        }
        ///    }
        ///
        ///    public void IfStatement()
        ///    {
        ///        var x = 1;
        ///
        ///        if (x == 1)
        ///        {
        ///        }
        ///    }
        ///
        ///    public void WhileStatement()
        ///    {
        ///        var x = 1;
        ///
        ///        while (x &gt; 0)
        ///        {
        ///            x--;
        ///        }
        ///    }
        ///
        ///    public void DoStatement()
        ///    {
        ///        var x = 1;
        ///
        ///        do
        ///        {
        ///            x--;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlankLineBeforeStatementResultData {
            get {
                return ResourceManager.GetString("BlankLineBeforeStatementResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to internal class BlankLineBeforeStatementTestData
        ///{
        ///    public void TryStatement()
        ///    {
        ///        var x = 1;
        ///        try
        ///        {
        ///        }
        ///        catch
        ///        {
        ///        }
        ///    }
        ///
        ///    public void IfStatement()
        ///    {
        ///        var x = 1;
        ///        if (x == 1)
        ///        {
        ///        }
        ///    }
        ///
        ///    public void WhileStatement()
        ///    {
        ///        var x = 1;
        ///        while (x &gt; 0)
        ///        {
        ///            x--;
        ///        }
        ///    }
        ///
        ///    public void DoStatement()
        ///    {
        ///        var x = 1;
        ///        do
        ///        {
        ///            x--;
        ///        }
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BlankLineBeforeStatementTestData {
            get {
                return ResourceManager.GetString("BlankLineBeforeStatementTestData", resourceCulture);
            }
        }
    }
}
