//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reihitsu.Formatter.Test.Integration.Rules.Indentation.Resources {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reihitsu.Formatter.Test.Integration.Rules.Indentation.Resources.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string IndentationTestData {
            get {
                return ResourceManager.GetString("IndentationTestData", resourceCulture);
            }
        }
        
        internal static string IndentationResultData {
            get {
                return ResourceManager.GetString("IndentationResultData", resourceCulture);
            }
        }
        
        internal static string ObjectInitializerLayoutTestData {
            get {
                return ResourceManager.GetString("ObjectInitializerLayoutTestData", resourceCulture);
            }
        }
        
        internal static string ObjectInitializerLayoutResultData {
            get {
                return ResourceManager.GetString("ObjectInitializerLayoutResultData", resourceCulture);
            }
        }
        
        internal static string MethodChainAlignmentTestData {
            get {
                return ResourceManager.GetString("MethodChainAlignmentTestData", resourceCulture);
            }
        }
        
        internal static string MethodChainAlignmentResultData {
            get {
                return ResourceManager.GetString("MethodChainAlignmentResultData", resourceCulture);
            }
        }
        
        internal static string LogicalExpressionLayoutTestData {
            get {
                return ResourceManager.GetString("LogicalExpressionLayoutTestData", resourceCulture);
            }
        }
        
        internal static string LogicalExpressionLayoutResultData {
            get {
                return ResourceManager.GetString("LogicalExpressionLayoutResultData", resourceCulture);
            }
        }
    }
}
