//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reihitsu.Analyzer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reihitsu.Analyzer.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanging ! operator with equals comparison.
        /// </summary>
        internal static string RH0001Title {
            get {
                return ResourceManager.GetString("RH0001Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanging property with a matching field.
        /// </summary>
        internal static string RH0101Title {
            get {
                return ResourceManager.GetString("RH0101Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename file to match type name.
        /// </summary>
        internal static string RH0201Title {
            get {
                return ResourceManager.GetString("RH0201Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0202Title {
            get {
                return ResourceManager.GetString("RH0202Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0203Title {
            get {
                return ResourceManager.GetString("RH0203Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0204Title {
            get {
                return ResourceManager.GetString("RH0204Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0205Title {
            get {
                return ResourceManager.GetString("RH0205Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0206Title {
            get {
                return ResourceManager.GetString("RH0206Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0207Title {
            get {
                return ResourceManager.GetString("RH0207Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0208Title {
            get {
                return ResourceManager.GetString("RH0208Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0209Title {
            get {
                return ResourceManager.GetString("RH0209Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0210Title {
            get {
                return ResourceManager.GetString("RH0210Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0211Title {
            get {
                return ResourceManager.GetString("RH0211Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0212Title {
            get {
                return ResourceManager.GetString("RH0212Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0213Title {
            get {
                return ResourceManager.GetString("RH0213Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0214Title {
            get {
                return ResourceManager.GetString("RH0214Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0215Title {
            get {
                return ResourceManager.GetString("RH0215Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0216Title {
            get {
                return ResourceManager.GetString("RH0216Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0217Title {
            get {
                return ResourceManager.GetString("RH0217Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0218Title {
            get {
                return ResourceManager.GetString("RH0218Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0219Title {
            get {
                return ResourceManager.GetString("RH0219Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0220Title {
            get {
                return ResourceManager.GetString("RH0220Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0221Title {
            get {
                return ResourceManager.GetString("RH0221Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0222Title {
            get {
                return ResourceManager.GetString("RH0222Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0223Title {
            get {
                return ResourceManager.GetString("RH0223Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix casing.
        /// </summary>
        internal static string RH0224Title {
            get {
                return ResourceManager.GetString("RH0224Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applying the description of the #region .
        /// </summary>
        internal static string RH0301Title {
            get {
                return ResourceManager.GetString("RH0301Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the indention of the initializer.
        /// </summary>
        internal static string RH0302Title {
            get {
                return ResourceManager.GetString("RH0302Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0303Title {
            get {
                return ResourceManager.GetString("RH0303Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0304Title {
            get {
                return ResourceManager.GetString("RH0304Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0305Title {
            get {
                return ResourceManager.GetString("RH0305Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0306Title {
            get {
                return ResourceManager.GetString("RH0306Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0307Title {
            get {
                return ResourceManager.GetString("RH0307Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0308Title {
            get {
                return ResourceManager.GetString("RH0308Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0309Title {
            get {
                return ResourceManager.GetString("RH0309Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0310Title {
            get {
                return ResourceManager.GetString("RH0310Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0311Title {
            get {
                return ResourceManager.GetString("RH0311Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0312Title {
            get {
                return ResourceManager.GetString("RH0312Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0314Title {
            get {
                return ResourceManager.GetString("RH0314Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0315Title {
            get {
                return ResourceManager.GetString("RH0315Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0316Title {
            get {
                return ResourceManager.GetString("RH0316Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0317Title {
            get {
                return ResourceManager.GetString("RH0317Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0318Title {
            get {
                return ResourceManager.GetString("RH0318Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0319Title {
            get {
                return ResourceManager.GetString("RH0319Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0320Title {
            get {
                return ResourceManager.GetString("RH0320Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insert blank line before statement.
        /// </summary>
        internal static string RH0321Title {
            get {
                return ResourceManager.GetString("RH0321Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align method chain.
        /// </summary>
        internal static string RH0324Title {
            get {
                return ResourceManager.GetString("RH0324Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to block body.
        /// </summary>
        internal static string RH0325Title {
            get {
                return ResourceManager.GetString("RH0325Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the alignment of the logical operator.
        /// </summary>
        internal static string RH0329Title {
            get {
                return ResourceManager.GetString("RH0329Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix the alignment of the raw string literal.
        /// </summary>
        internal static string RH0330Title {
            get {
                return ResourceManager.GetString("RH0330Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Move the first argument to the same line.
        /// </summary>
        internal static string RH0331Title {
            get {
                return ResourceManager.GetString("RH0331Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Place each argument on its own line.
        /// </summary>
        internal static string RH0332Title {
            get {
                return ResourceManager.GetString("RH0332Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Align the arguments.
        /// </summary>
        internal static string RH0333Title {
            get {
                return ResourceManager.GetString("RH0333Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Replace documentation with &lt;inheritdoc/&gt;.
        /// </summary>
        internal static string RH0401Title {
            get {
                return ResourceManager.GetString("RH0401Title", resourceCulture);
            }
        }
    }
}
