using Microsoft.CodeAnalysis;

namespace Reihitsu.Cli.Abstractions;

/// <summary>
/// Abstracts the formatting engine for testability
/// </summary>
internal interface ISourceFormatter
{
    #region Methods

    /// <summary>
    /// Formats a syntax tree and returns the formatted tree
    /// </summary>
    /// <param name="syntaxTree">The syntax tree to format</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests</param>
    /// <returns>The formatted syntax tree</returns>
    SyntaxTree FormatSyntaxTree(SyntaxTree syntaxTree, CancellationToken cancellationToken);

    /// <summary>
    /// Determines whether a syntax tree is marked as auto-generated and should not be formatted
    /// </summary>
    /// <param name="syntaxTree">The syntax tree to inspect</param>
    /// <param name="cancellationToken">A token to monitor for cancellation requests</param>
    /// <returns><see langword="true"/> if the syntax tree is marked as auto-generated; otherwise, <see langword="false"/></returns>
    bool IsAutoGeneratedSource(SyntaxTree syntaxTree, CancellationToken cancellationToken);

    #endregion // Methods
}