using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Reihitsu.Formatter.Test.Unit;

/// <summary>
/// Tests for <see cref="ReihitsuFormatterHelpers"/>
/// </summary>
[TestClass]
public class ReihitsuFormatterHelpersTests
{
    #region Properties

    /// <summary>
    /// Gets or sets the test context for the current test.
    /// </summary>
    public TestContext TestContext { get; set; }

    #endregion // Properties

    #region Methods

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.DetectEndOfLine"/> returns LF when the source uses LF line endings.
    /// </summary>
    [TestMethod]
    public void DetectEndOfLineReturnsLineFeedWhenSourceUsesLineFeed()
    {
        // Arrange
        const string input = "namespace Test;\nclass Foo { }\n";

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.DetectEndOfLine(root);

        // Assert
        Assert.AreEqual("\n", result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.DetectEndOfLine"/> returns CRLF when the source uses CRLF line endings.
    /// </summary>
    [TestMethod]
    public void DetectEndOfLineReturnsCarriageReturnLineFeedWhenSourceUsesCarriageReturnLineFeed()
    {
        // Arrange
        const string input = "namespace Test;\r\nclass Foo { }\r\n";

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.DetectEndOfLine(root);

        // Assert
        Assert.AreEqual("\r\n", result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.DetectEndOfLine"/> falls back to <see cref="System.Environment.NewLine"/> when no end-of-line trivia is found.
    /// </summary>
    [TestMethod]
    public void DetectEndOfLineFallsBackToEnvironmentNewLineWhenNoEndOfLineTriviaFound()
    {
        // Arrange
        const string input = "class Foo { }";

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.DetectEndOfLine(root);

        // Assert
        Assert.AreEqual(System.Environment.NewLine, result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.HasSyntaxErrors"/> returns true when the syntax tree contains errors.
    /// </summary>
    [TestMethod]
    public void HasSyntaxErrorsReturnsTrueWhenTreeContainsErrors()
    {
        // Arrange
        const string input = """
                             namespace Test;

                             public class Foo
                             {
                                 public void Bar(
                                 {
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.HasSyntaxErrors(tree);

        // Assert
        Assert.IsTrue(result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.HasSyntaxErrors"/> returns false when the syntax tree is valid.
    /// </summary>
    [TestMethod]
    public void HasSyntaxErrorsReturnsFalseWhenTreeIsValid()
    {
        // Arrange
        const string input = """
                             namespace Test;

                             public class Foo
                             {
                                 public void Bar()
                                 {
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.HasSyntaxErrors(tree);

        // Assert
        Assert.IsFalse(result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.IsAutoGeneratedSource"/> returns true for a single-line auto-generated marker.
    /// </summary>
    [TestMethod]
    public void IsAutoGeneratedSourceReturnsTrueForSingleLineMarker()
    {
        // Arrange
        const string input = """
                             // <auto-generated />
                             namespace Test;

                             public class Foo { }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.IsAutoGeneratedSource(root);

        // Assert
        Assert.IsTrue(result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.IsAutoGeneratedSource"/> returns true for a multi-line auto-generated marker.
    /// </summary>
    [TestMethod]
    public void IsAutoGeneratedSourceReturnsTrueForMultiLineMarker()
    {
        // Arrange
        const string input = """
                             /*
                              * <auto-generated>
                              *     This code was generated by a tool.
                              * </auto-generated>
                              */
                             namespace Test;

                             public class Foo { }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.IsAutoGeneratedSource(root);

        // Assert
        Assert.IsTrue(result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.IsAutoGeneratedSource"/> returns true for the autogenerated marker without hyphen.
    /// </summary>
    [TestMethod]
    public void IsAutoGeneratedSourceReturnsTrueForAutogeneratedMarkerWithoutHyphen()
    {
        // Arrange
        const string input = """
                             // <autogenerated />
                             namespace Test;

                             public class Foo { }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.IsAutoGeneratedSource(root);

        // Assert
        Assert.IsTrue(result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.IsAutoGeneratedSource"/> returns false when no auto-generated marker is present.
    /// </summary>
    [TestMethod]
    public void IsAutoGeneratedSourceReturnsFalseWhenNoMarkerIsPresent()
    {
        // Arrange
        const string input = """
                             namespace Test;

                             public class Foo { }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.IsAutoGeneratedSource(root);

        // Assert
        Assert.IsFalse(result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.IsAutoGeneratedSource"/> is case-insensitive.
    /// </summary>
    [TestMethod]
    public void IsAutoGeneratedSourceIsCaseInsensitive()
    {
        // Arrange
        const string input = """
                             // <AUTO-GENERATED />
                             namespace Test;

                             public class Foo { }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatterHelpers.IsAutoGeneratedSource(root);

        // Assert
        Assert.IsTrue(result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.ComputeBaseIndentLevel"/> returns zero for a top-level member in a file-scoped namespace.
    /// </summary>
    [TestMethod]
    public void ComputeBaseIndentLevelReturnsZeroForTopLevelMemberInFileScopedNamespace()
    {
        // Arrange
        const string input = """
                             namespace Test;

                             class Foo { }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var classDecl = root.DescendantNodes().OfType<ClassDeclarationSyntax>().First();

        // Act
        var result = ReihitsuFormatterHelpers.ComputeBaseIndentLevel(classDecl);

        // Assert
        Assert.AreEqual(0, result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.ComputeBaseIndentLevel"/> returns one for a member inside a block-scoped namespace.
    /// </summary>
    [TestMethod]
    public void ComputeBaseIndentLevelReturnsOneForMemberInsideBlockScopedNamespace()
    {
        // Arrange
        const string input = """
                             namespace Test
                             {
                                 class Foo { }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var classDecl = root.DescendantNodes().OfType<ClassDeclarationSyntax>().First();

        // Act
        var result = ReihitsuFormatterHelpers.ComputeBaseIndentLevel(classDecl);

        // Assert
        Assert.AreEqual(1, result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.ComputeBaseIndentLevel"/> returns two for a method inside a class inside a block-scoped namespace.
    /// </summary>
    [TestMethod]
    public void ComputeBaseIndentLevelReturnsTwoForMethodInsideClassInsideBlockScopedNamespace()
    {
        // Arrange
        const string input = """
                             namespace Test
                             {
                                 class Foo
                                 {
                                     void Bar() { }
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var methodDecl = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();

        // Act
        var result = ReihitsuFormatterHelpers.ComputeBaseIndentLevel(methodDecl);

        // Assert
        Assert.AreEqual(2, result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.ComputeBaseIndentLevel"/> counts nested types correctly.
    /// </summary>
    [TestMethod]
    public void ComputeBaseIndentLevelCountsNestedTypesCorrectly()
    {
        // Arrange
        const string input = """
                             namespace Test
                             {
                                 class Outer
                                 {
                                     class Inner
                                     {
                                         void Bar() { }
                                     }
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var methodDecl = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();

        // Act
        var result = ReihitsuFormatterHelpers.ComputeBaseIndentLevel(methodDecl);

        // Assert
        Assert.AreEqual(3, result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.ComputeTokenColumn"/> returns zero for a token at the beginning of a line.
    /// </summary>
    [TestMethod]
    public void ComputeTokenColumnReturnsZeroForTokenAtBeginningOfLine()
    {
        // Arrange
        const string input = "class Foo { }";

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var classKeyword = root.DescendantTokens().First(t => t.IsKind(SyntaxKind.ClassKeyword));

        // Act
        var result = ReihitsuFormatterHelpers.ComputeTokenColumn(classKeyword, root);

        // Assert
        Assert.AreEqual(0, result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.ComputeTokenColumn"/> returns the correct column for an indented token.
    /// </summary>
    [TestMethod]
    public void ComputeTokenColumnReturnsCorrectColumnForIndentedToken()
    {
        // Arrange
        const string input = """
                             namespace Test;
                                 class Foo { }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var classKeyword = root.DescendantTokens().First(t => t.IsKind(SyntaxKind.ClassKeyword));

        // Act
        var result = ReihitsuFormatterHelpers.ComputeTokenColumn(classKeyword, root);

        // Assert
        Assert.AreEqual(4, result);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.AdjustNodeIndentation"/> shifts indentation right by the given offset.
    /// </summary>
    [TestMethod]
    public void AdjustNodeIndentationShiftsIndentationRightByOffset()
    {
        // Arrange
        const string input = """
                             class Foo
                             {
                                 void Bar()
                                 {
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var methodDecl = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();

        // Act
        var result = ReihitsuFormatterHelpers.AdjustNodeIndentation(methodDecl, 4);
        var resultText = result.ToFullString();

        // Assert
        Assert.Contains("        void Bar()", resultText, "Method declaration should be shifted right by 4 spaces.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.AdjustNodeIndentation"/> shifts indentation left by the given offset.
    /// </summary>
    [TestMethod]
    public void AdjustNodeIndentationShiftsIndentationLeftByOffset()
    {
        // Arrange
        const string input = """
                             class Foo
                             {
                                     void Bar()
                                     {
                                     }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var methodDecl = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();

        // Act
        var result = ReihitsuFormatterHelpers.AdjustNodeIndentation(methodDecl, -4);
        var resultText = result.ToFullString();

        // Assert
        Assert.Contains("    void Bar()", resultText, "Method declaration should be shifted left by 4 spaces.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.AdjustNodeIndentation"/> returns the node unchanged when there are no tokens on new lines.
    /// </summary>
    [TestMethod]
    public void AdjustNodeIndentationReturnsUnchangedNodeWhenNoTokensOnNewLines()
    {
        // Arrange
        const string input = "class Foo { void Bar() { } }";

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var methodDecl = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();
        var originalText = methodDecl.ToFullString();

        // Act
        var result = ReihitsuFormatterHelpers.AdjustNodeIndentation(methodDecl, 4);
        var resultText = result.ToFullString();

        // Assert
        Assert.AreEqual(originalText, resultText);
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatterHelpers.AdjustNodeIndentation"/> does not produce negative indentation.
    /// </summary>
    [TestMethod]
    public void AdjustNodeIndentationDoesNotProduceNegativeIndentation()
    {
        // Arrange
        const string input = """
                             class Foo
                             {
                               void Bar()
                               {
                               }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var methodDecl = root.DescendantNodes().OfType<MethodDeclarationSyntax>().First();

        // Act
        var result = ReihitsuFormatterHelpers.AdjustNodeIndentation(methodDecl, -100);
        var resultText = result.ToFullString();

        // Assert — should not throw and indentation should be clamped to zero
        Assert.Contains("void Bar()", resultText, "Method declaration should still be present.");
    }

    #endregion // Methods
}