using System.Threading.Tasks;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Reihitsu.Formatter.Test.Helpers;

namespace Reihitsu.Formatter.Test.Unit;

/// <summary>
/// Tests for <see cref="ReihitsuFormatter"/>
/// </summary>
[TestClass]
public class ReihitsuFormatterTests : FormatterTestsBase
{
    #region Properties

    /// <summary>
    /// Gets or sets the test context for the current test
    /// </summary>
    public TestContext TestContext { get; set; }

    #endregion // Properties

    #region Methods

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> returns the original tree when the input contains syntax errors
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeWithSyntaxErrorsReturnsOriginalTree()
    {
        // Arrange
        const string input = """
                             namespace Test;

                             public class Foo
                             {
                                 public void Bar(
                                 {
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);

        // Assert
        Assert.AreSame(tree, result, "Tree with syntax errors should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> returns the original tree when the source contains a single-line auto-generated marker
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeWithSingleLineAutoGeneratedMarkerReturnsOriginalTree()
    {
        // Arrange
        const string input = """
                             // <auto-generated />
                             namespace Test;
                             
                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var value = 1;
                                     return value;
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);

        // Assert
        Assert.AreSame(tree, result, "Tree with single-line auto-generated marker should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> returns the original tree when the source contains a multi-line auto-generated marker
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeWithMultiLineAutoGeneratedMarkerReturnsOriginalTree()
    {
        // Arrange
        const string input = """
                             /*
                              * <auto-generated>
                              *     This code was generated by a tool.
                              * </auto-generated>
                              */
                             namespace Test;
                             
                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var value = 1;
                                     return value;
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);

        // Assert
        Assert.AreSame(tree, result, "Tree with multi-line auto-generated marker should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> applies formatting to valid input
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeValidInputReturnsFormattedTree()
    {
        // Arrange — missing blank line before `return`
        const string input = """
                             namespace Test;

                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var x = 1;
                                     return x;
                                 }
                             }
                             """;
        const string expected = """
                                namespace Test;

                                public class Foo
                                {
                                    public int Bar()
                                    {
                                        var x = 1;

                                        return x;
                                    }
                                }
                                """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert
        Assert.AreEqual(expected, actual, "Formatter output should match the fully formatted code.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> handles an empty file without throwing exceptions
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeEmptyFileDoesNotThrow()
    {
        // Arrange
        var input = string.Empty;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert — the formatter may normalize the file (e.g. add a trailing newline),
        // but it must not throw or produce syntax errors.
        Assert.IsFalse(result.GetDiagnostics(TestContext.CancellationTokenSource.Token).Any(d => d.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error), "Formatted empty file should not have syntax errors.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatNode"/> formats a given syntax node
    /// </summary>
    [TestMethod]
    public void FormatNodeFormatsGivenNode()
    {
        // Arrange — method with missing blank line before return
        const string input = """
                             namespace Test;
                    
                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var x = 1;
                                     return x;
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var methodNode = root.DescendantNodes().OfType<MethodDeclarationSyntax>().Single();

        // Act
        var result = ReihitsuFormatter.FormatNode(methodNode, cancellationToken: TestContext.CancellationTokenSource.Token);
        var actual = result.ToFullString();

        // Assert
        Assert.AreNotEqual(methodNode.ToFullString(), actual, "FormatNode should have modified the method node.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatNode"/> formats documentation comments for detached/generated nodes
    /// </summary>
    [TestMethod]
    public void FormatNodeWithDetachedDocumentationCommentNodeFormatsWithSynthesizedSyntaxTree()
    {
        // Arrange
        const string expectedDocumentationComment = """
                                                    /// <summary>
                                                    /// Summary text
                                                    /// </summary>
                                                    """;
        var detachedMethodNode = SyntaxFactory.MethodDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)), SyntaxFactory.Identifier("Foo"))
                                              .WithModifiers(SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.PublicKeyword)))
                                              .WithLeadingTrivia(SyntaxFactory.ParseLeadingTrivia("""
                                                                                                  /// <summary>Summary text</summary>
                                                                                                  """))
                                              .WithBody(SyntaxFactory.Block());

        if (detachedMethodNode.Parent != null)
        {
            Assert.Fail("Test setup must use a detached/generated node.");
        }

        Assert.IsNotNull(detachedMethodNode.SyntaxTree, "Detached/generated nodes should receive a synthesized syntax tree from Roslyn.");

        // Act
        var result = ReihitsuFormatter.FormatNode(detachedMethodNode, cancellationToken: TestContext.CancellationTokenSource.Token);
        var actual = result.ToFullString();

        // Assert
        Assert.AreEqual("Foo", ((MethodDeclarationSyntax)result).Identifier.ValueText, "Detached/generated node identity should be preserved.");
        Assert.Contains(expectedDocumentationComment, actual, "Documentation comments should be normalized for detached/generated nodes.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatNode"/> aligns raw strings for detached/generated nodes
    /// </summary>
    [TestMethod]
    public void FormatNodeWithDetachedRawStringNodeFormatsWithSynthesizedSyntaxTree()
    {
        // Arrange
        var rawStringStatement = SyntaxFactory.ParseStatement(""""
                                                              var text = """
                                                              Hello
                                                              """;
                                                              """");
        var detachedMethodNode = SyntaxFactory.MethodDeclaration(SyntaxFactory.PredefinedType(SyntaxFactory.Token(SyntaxKind.VoidKeyword)), SyntaxFactory.Identifier("Foo"))
                                              .WithModifiers(SyntaxFactory.TokenList(SyntaxFactory.Token(SyntaxKind.PublicKeyword)))
                                              .WithBody(SyntaxFactory.Block(rawStringStatement));

        if (detachedMethodNode.Parent != null)
        {
            Assert.Fail("Test setup must use a detached/generated node.");
        }

        Assert.IsNotNull(detachedMethodNode.SyntaxTree, "Detached/generated nodes should receive a synthesized syntax tree from Roslyn.");

        // Act
        var result = ReihitsuFormatter.FormatNode(detachedMethodNode, cancellationToken: TestContext.CancellationTokenSource.Token);
        var rawStringToken = result.DescendantNodes()
                                   .OfType<LiteralExpressionSyntax>()
                                   .Single()
                                   .Token;
        var rawStringLines = rawStringToken.Text.Split('\n');
        var openingColumn = rawStringToken.GetLocation().GetLineSpan().StartLinePosition.Character;
        var contentColumn = rawStringLines[1].TakeWhile(ch => ch == ' ').Count();
        var closingColumn = rawStringLines[^1].TakeWhile(ch => ch == ' ').Count();

        // Assert
        Assert.AreEqual("Foo", ((MethodDeclarationSyntax)result).Identifier.ValueText, "Detached/generated node identity should be preserved.");
        Assert.AreEqual(openingColumn, contentColumn, "Raw string content should align with the opening delimiter for detached/generated nodes.");
        Assert.AreEqual(openingColumn, closingColumn, "Raw string closing delimiter should align with the opening delimiter for detached/generated nodes.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatDocumentAsync"/> returns the original document when it contains syntax errors
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatDocumentAsyncWithSyntaxErrorsReturnsOriginalDocument()
    {
        // Arrange
        const string input = """
                             namespace Test;

                             public class Foo
                             {
                                 public void Bar(
                                 {
                                 }
                             }
                             """;

        using (var workspace = new AdhocWorkspace())
        {
            var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
            var document = project.AddDocument("Test.cs", SourceText.From(input));

            // Act
            var result = await ReihitsuFormatter.FormatDocumentAsync(document, TestContext.CancellationTokenSource.Token);

            // Assert
            var originalText = await document.GetTextAsync(TestContext.CancellationTokenSource.Token);
            var resultText = await result.GetTextAsync(TestContext.CancellationTokenSource.Token);

            Assert.AreEqual(originalText.ToString(), resultText.ToString(), "Document with syntax errors should be returned unchanged.");
        }
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatDocumentAsync"/> returns the original document when the source contains an auto-generated marker
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatDocumentAsyncWithAutoGeneratedMarkerReturnsOriginalDocument()
    {
        // Arrange
        const string input = """
                             // <auto-generated />
                             namespace Test;
                             
                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var value = 1;
                                     return value;
                                 }
                             }
                             """;

        using var workspace = new AdhocWorkspace();

        var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
        var document = project.AddDocument("Test.cs", SourceText.From(input));

        // Act
        var result = await ReihitsuFormatter.FormatDocumentAsync(document, TestContext.CancellationTokenSource.Token);

        // Assert
        var originalText = await document.GetTextAsync(TestContext.CancellationTokenSource.Token);
        var resultText = await result.GetTextAsync(TestContext.CancellationTokenSource.Token);

        Assert.AreEqual(originalText.ToString(), resultText.ToString(), "Document with auto-generated marker should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatDocumentAsync"/> applies formatting to a valid document
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatDocumentAsyncValidInputReturnsFormattedDocument()
    {
        // Arrange — missing blank line before `return`
        const string input = """
                             namespace Test;

                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var x = 1;
                                     return x;
                                 }
                             }
                             """;
        const string expected = """
                                namespace Test;

                                public class Foo
                                {
                                    public int Bar()
                                    {
                                        var x = 1;

                                        return x;
                                    }
                                }
                                """;

        using var workspace = new AdhocWorkspace();

        var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
        var document = project.AddDocument("Test.cs", SourceText.From(input));

        // Act
        var result = await ReihitsuFormatter.FormatDocumentAsync(document, TestContext.CancellationTokenSource.Token);
        var resultText = (await result.GetTextAsync(TestContext.CancellationTokenSource.Token)).ToString();

        // Assert
        Assert.AreEqual(expected, resultText, "Formatter output should match the fully formatted document.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatNodeInDocumentAsync"/> keeps blank-line changes scoped to the target node
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatNodeInDocumentAsyncKeepsBlankLineChangesScopedToTargetNode()
    {
        // Arrange
        const string input = """
                             using System;
                             namespace Test
                             {
                                 public class Foo
                                 {
                                     public int Bar()
                                     {
                                         var x = 1;
                                         return x;
                                     }
                                 }
                             }
                             """;
        const string expected = """
                                using System;
                                namespace Test
                                {
                                    public class Foo
                                    {
                                        public int Bar()
                                        {
                                            var x = 1;

                                            return x;
                                        }
                                    }
                                }
                                """;

        using var workspace = new AdhocWorkspace();

        var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
        var document = project.AddDocument("Test.cs", SourceText.From(input));
        var root = await document.GetSyntaxRootAsync(TestContext.CancellationTokenSource.Token);
        var namespaceDeclaration = root?.DescendantNodes().OfType<NamespaceDeclarationSyntax>().Single();

        if (namespaceDeclaration == null)
        {
            Assert.Fail("Expected a namespace declaration in the test document.");
        }

        // Act
        var result = await ReihitsuFormatter.FormatNodeInDocumentAsync(document, namespaceDeclaration, TestContext.CancellationTokenSource.Token);
        var resultText = (await result.GetTextAsync(TestContext.CancellationTokenSource.Token)).ToString();

        // Assert
        Assert.AreEqual(expected, resultText, "Only blank-line changes within the namespace should be applied.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatNodeInDocumentAsync"/> keeps using-ordering changes scoped to the target node
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatNodeInDocumentAsyncKeepsUsingOrderingChangesScopedToTargetNode()
    {
        // Arrange
        const string input = """
                             using Zeta;
                             using Alpha;

                             namespace Test
                             {
                                 using Zeta;
                                 using Alpha;

                                 public class Foo
                                 {
                                     public int Bar()
                                     {
                                         var x = 1;
                                         return x;
                                     }
                                 }
                             }
                             """;
        const string expected = """
                                using Zeta;
                                using Alpha;

                                namespace Test
                                {
                                    using Alpha;

                                    using Zeta;

                                    public class Foo
                                    {
                                        public int Bar()
                                        {
                                            var x = 1;

                                            return x;
                                        }
                                    }
                                }
                                """;

        using var workspace = new AdhocWorkspace();

        var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
        var document = project.AddDocument("Test.cs", SourceText.From(input));
        var root = await document.GetSyntaxRootAsync(TestContext.CancellationTokenSource.Token);
        var namespaceDeclaration = root?.DescendantNodes().OfType<NamespaceDeclarationSyntax>().Single();

        if (namespaceDeclaration == null)
        {
            Assert.Fail("Expected a namespace declaration in the test document.");
        }

        // Act
        var result = await ReihitsuFormatter.FormatNodeInDocumentAsync(document, namespaceDeclaration, TestContext.CancellationTokenSource.Token);
        var resultText = (await result.GetTextAsync(TestContext.CancellationTokenSource.Token)).ToString();

        // Assert
        Assert.AreEqual(expected, resultText, "Only using directives within the namespace should be reordered.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatNodeInDocumentAsync"/> aligns raw strings within the target node without touching sibling members
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatNodeInDocumentAsyncAlignsRawStringsWithinTargetNode()
    {
        // Arrange
        var input = CrLf(""""
                         namespace Test;

                         public class Foo
                         {
                             public string First()
                             {
                                 return """
                         Hello
                         """;
                             }

                             public string Second()
                             {
                                 return """
                         World
                         """;
                             }
                         }
                         """");

        using var workspace = new AdhocWorkspace();

        var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
        var document = project.AddDocument("Test.cs", SourceText.From(input));
        var root = await document.GetSyntaxRootAsync(TestContext.CancellationTokenSource.Token);
        var methods = root?.DescendantNodes().OfType<MethodDeclarationSyntax>().ToArray();

        if (methods == null || methods.Length != 2)
        {
            Assert.Fail("Expected two method declarations in the test document.");
        }

        var originalSecondRawString = methods[1].DescendantNodes()
                                                .OfType<LiteralExpressionSyntax>()
                                                .Single()
                                                .Token.Text;

        // Act
        var result = await ReihitsuFormatter.FormatNodeInDocumentAsync(document, methods[0], TestContext.CancellationTokenSource.Token);
        var resultRoot = await result.GetSyntaxRootAsync(TestContext.CancellationTokenSource.Token);
        var resultMethods = resultRoot?.DescendantNodes().OfType<MethodDeclarationSyntax>().ToArray();

        if (resultMethods == null || resultMethods.Length != 2)
        {
            Assert.Fail("Expected two method declarations in the formatted document.");
        }

        var formattedFirstRawString = resultMethods[0].DescendantNodes()
                                                      .OfType<LiteralExpressionSyntax>()
                                                      .Single()
                                                      .Token;
        var formattedSecondRawString = resultMethods[1].DescendantNodes()
                                                       .OfType<LiteralExpressionSyntax>()
                                                       .Single()
                                                       .Token.Text;
        var rawStringLines = formattedFirstRawString.Text.Split('\n');
        var openingColumn = formattedFirstRawString.GetLocation().GetLineSpan().StartLinePosition.Character;
        var contentColumn = rawStringLines[1].TakeWhile(ch => ch == ' ').Count();
        var closingColumn = rawStringLines[^1].TakeWhile(ch => ch == ' ').Count();

        // Assert
        Assert.AreEqual(openingColumn, contentColumn, "Targeted raw-string content should align with the opening delimiter.");
        Assert.AreEqual(openingColumn, closingColumn, "Targeted raw-string closing delimiter should align with the opening delimiter.");
        Assert.AreEqual(originalSecondRawString, formattedSecondRawString, "Only the targeted method should receive raw-string alignment changes.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> preserves \r\n line endings
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeDetectsCarriageReturnLineFeed()
    {
        // Arrange — input uses \r\n line endings
        var input = CrLf("""
                         namespace Test;

                         public class Foo
                         {
                             public int Bar()
                             {
                                 var x = 1;
                                 return x;
                             }
                         }
                         """);
        var expected = CrLf("""
                            namespace Test;

                            public class Foo
                            {
                                public int Bar()
                                {
                                    var x = 1;

                                    return x;
                                }
                            }
                            """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert
        Assert.AreEqual(expected, actual, "Output should preserve CRLF line endings and full formatted content.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> preserves \n line endings
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeDetectsLineFeed()
    {
        // Arrange — input uses \n line endings
        var input = Lf("""
                       namespace Test;

                       public class Foo
                       {
                           public int Bar()
                           {
                               var x = 1;
                               return x;
                           }
                       }
                       """);
        var expected = Lf("""
                          namespace Test;

                          public class Foo
                          {
                              public int Bar()
                              {
                                  var x = 1;

                                  return x;
                              }
                          }
                          """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert
        Assert.AreEqual(expected, actual, "Output should preserve LF line endings and full formatted content.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> normalizes mixed line endings to the predominant style
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeNormalizesMixedLineEndingsToPredominantStyle()
    {
        // Arrange — the source mixes CRLF and LF, but LF is predominant
        const string input = "namespace Test;\n\npublic class Foo\r\n{\n    public int Bar()\r\n    {\n        var x = 1;\r\n        return x;\n    }\n}\r\n";
        var expected = Lf("""
                          namespace Test;

                          public class Foo
                          {
                              public int Bar()
                              {
                                  var x = 1;

                                  return x;
                              }
                          }
                          """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert
        Assert.AreEqual(expected, actual, "Output should normalize all line endings to the predominant style.");
        Assert.DoesNotContain("\r\n", actual, "Output should not contain non-predominant CRLF line endings.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> throws <see cref="OperationCanceledException"/> when cancellation is requested
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeCancellationRequestedThrowsOperationCanceled()
    {
        // Arrange
        var input = CrLf("""
                         namespace Test;

                         public class Foo
                         {
                             public int Bar()
                             {
                                 var x = 1;
                                 return x;
                             }
                         }
                         """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        using (var cts = new System.Threading.CancellationTokenSource())
        {
            cts.Cancel();

            Assert.ThrowsExactly<OperationCanceledException>(() => ReihitsuFormatter.FormatSyntaxTree(tree, cts.Token));
        }
    }

    /// <summary>
    /// Normalizes line endings in the provided text to LF
    /// </summary>
    /// <param name="text">The text to normalize</param>
    /// <returns>The text with LF line endings</returns>
    private static string Lf(string text)
    {
        return text.Replace("\r\n", "\n");
    }

    /// <summary>
    /// Normalizes line endings in the provided text to CRLF
    /// </summary>
    /// <param name="text">The text to normalize</param>
    /// <returns>The text with CRLF line endings</returns>
    private static string CrLf(string text)
    {
        return Lf(text).Replace("\n", "\r\n");
    }

    #endregion // Methods
}