using System.Threading.Tasks;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using Microsoft.VisualStudio.TestTools.UnitTesting;

using Reihitsu.Formatter.Test.Helpers;

namespace Reihitsu.Formatter.Test.Unit;

/// <summary>
/// Tests for <see cref="ReihitsuFormatter"/>
/// </summary>
[TestClass]
public class ReihitsuFormatterTests : FormatterTestsBase
{
    #region Properties

    /// <summary>
    /// Gets or sets the test context for the current test
    /// </summary>
    public TestContext TestContext { get; set; }

    #endregion // Properties

    #region Methods

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> returns the original tree when the input contains syntax errors
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeWithSyntaxErrorsReturnsOriginalTree()
    {
        // Arrange
        const string input = """
                             namespace Test;

                             public class Foo
                             {
                                 public void Bar(
                                 {
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);

        // Assert
        Assert.AreSame(tree, result, "Tree with syntax errors should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> returns the original tree when the source contains a single-line auto-generated marker
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeWithSingleLineAutoGeneratedMarkerReturnsOriginalTree()
    {
        // Arrange
        const string input = """
                             // <auto-generated />
                             namespace Test;
                             
                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var value = 1;
                                     return value;
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);

        // Assert
        Assert.AreSame(tree, result, "Tree with single-line auto-generated marker should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> returns the original tree when the source contains a multi-line auto-generated marker
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeWithMultiLineAutoGeneratedMarkerReturnsOriginalTree()
    {
        // Arrange
        const string input = """
                             /*
                              * <auto-generated>
                              *     This code was generated by a tool.
                              * </auto-generated>
                              */
                             namespace Test;
                             
                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var value = 1;
                                     return value;
                                 }
                             }
                             """;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);

        // Assert
        Assert.AreSame(tree, result, "Tree with multi-line auto-generated marker should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> applies formatting to valid input
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeValidInputReturnsFormattedTree()
    {
        // Arrange — missing blank line before `return`
        var input = CrLf("""
                         namespace Test;

                         public class Foo
                         {
                             public int Bar()
                             {
                                 var x = 1;
                                 return x;
                             }
                         }
                         """);
        var expected = CrLf("""
                            namespace Test;

                            public class Foo
                            {
                                public int Bar()
                                {
                                    var x = 1;

                                    return x;
                                }
                            }
                            """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert
        Assert.AreEqual(expected, actual, "Formatter output should match the fully formatted code.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> handles an empty file without throwing exceptions
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeEmptyFileDoesNotThrow()
    {
        // Arrange
        var input = string.Empty;

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert — the formatter may normalize the file (e.g. add a trailing newline),
        // but it must not throw or produce syntax errors.
        Assert.IsFalse(result.GetDiagnostics(TestContext.CancellationTokenSource.Token).Any(d => d.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error), "Formatted empty file should not have syntax errors.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatNode"/> formats a given syntax node
    /// </summary>
    [TestMethod]
    public void FormatNodeFormatsGivenNode()
    {
        // Arrange — method with missing blank line before return
        var input = CrLf("""
                         namespace Test;

                         public class Foo
                         {
                             public int Bar()
                             {
                                 var x = 1;
                                 return x;
                             }
                         }
                         """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);
        var root = tree.GetRoot(TestContext.CancellationTokenSource.Token);
        var methodNode = root.DescendantNodes().First(n => n is Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax);

        // Act
        var result = ReihitsuFormatter.FormatNode(methodNode, cancellationToken: TestContext.CancellationTokenSource.Token);
        var actual = result.ToFullString();

        // Assert
        Assert.AreNotEqual(methodNode.ToFullString(), actual, "FormatNode should have modified the method node.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatDocumentAsync"/> returns the original document when it contains syntax errors
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatDocumentAsyncWithSyntaxErrorsReturnsOriginalDocument()
    {
        // Arrange
        const string input = """
                             namespace Test;

                             public class Foo
                             {
                                 public void Bar(
                                 {
                                 }
                             }
                             """;

        using var workspace = new AdhocWorkspace();

        var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
        var document = project.AddDocument("Test.cs", SourceText.From(input));

        // Act
        var result = await ReihitsuFormatter.FormatDocumentAsync(document, TestContext.CancellationTokenSource.Token);

        // Assert
        var originalText = await document.GetTextAsync(TestContext.CancellationTokenSource.Token);
        var resultText = await result.GetTextAsync(TestContext.CancellationTokenSource.Token);

        Assert.AreEqual(originalText.ToString(), resultText.ToString(), "Document with syntax errors should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatDocumentAsync"/> returns the original document when the source contains an auto-generated marker
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatDocumentAsyncWithAutoGeneratedMarkerReturnsOriginalDocument()
    {
        // Arrange
        const string input = """
                             // <auto-generated />
                             namespace Test;
                             
                             public class Foo
                             {
                                 public int Bar()
                                 {
                                     var value = 1;
                                     return value;
                                 }
                             }
                             """;

        using var workspace = new AdhocWorkspace();

        var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
        var document = project.AddDocument("Test.cs", SourceText.From(input));

        // Act
        var result = await ReihitsuFormatter.FormatDocumentAsync(document, TestContext.CancellationTokenSource.Token);

        // Assert
        var originalText = await document.GetTextAsync(TestContext.CancellationTokenSource.Token);
        var resultText = await result.GetTextAsync(TestContext.CancellationTokenSource.Token);

        Assert.AreEqual(originalText.ToString(), resultText.ToString(), "Document with auto-generated marker should be returned unchanged.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatDocumentAsync"/> applies formatting to a valid document
    /// </summary>
    /// <returns>A <see cref="Task"/> representing the asynchronous unit test</returns>
    [TestMethod]
    public async Task FormatDocumentAsyncValidInputReturnsFormattedDocument()
    {
        // Arrange — missing blank line before `return`
        var input = CrLf("""
                         namespace Test;

                         public class Foo
                         {
                             public int Bar()
                             {
                                 var x = 1;
                                 return x;
                             }
                         }
                         """);
        var expected = CrLf("""
                            namespace Test;

                            public class Foo
                            {
                                public int Bar()
                                {
                                    var x = 1;

                                    return x;
                                }
                            }
                            """);

        using var workspace = new AdhocWorkspace();

        var project = workspace.AddProject("TestProject", LanguageNames.CSharp);
        var document = project.AddDocument("Test.cs", SourceText.From(input));

        // Act
        var result = await ReihitsuFormatter.FormatDocumentAsync(document, TestContext.CancellationTokenSource.Token);
        var resultText = (await result.GetTextAsync(TestContext.CancellationTokenSource.Token)).ToString();

        // Assert
        Assert.AreEqual(expected, resultText, "Formatter output should match the fully formatted document.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> preserves \r\n line endings
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeDetectsCarriageReturnLineFeed()
    {
        // Arrange — input uses \r\n line endings
        var input = CrLf("""
                         namespace Test;

                         public class Foo
                         {
                             public int Bar()
                             {
                                 var x = 1;
                                 return x;
                             }
                         }
                         """);
        var expected = CrLf("""
                            namespace Test;

                            public class Foo
                            {
                                public int Bar()
                                {
                                    var x = 1;

                                    return x;
                                }
                            }
                            """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert
        Assert.AreEqual(expected, actual, "Output should preserve CRLF line endings and full formatted content.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> preserves \n line endings
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeDetectsLineFeed()
    {
        // Arrange — input uses \n line endings
        var input = Lf("""
                       namespace Test;

                       public class Foo
                       {
                           public int Bar()
                           {
                               var x = 1;
                               return x;
                           }
                       }
                       """);
        var expected = Lf("""
                          namespace Test;

                          public class Foo
                          {
                              public int Bar()
                              {
                                  var x = 1;

                                  return x;
                              }
                          }
                          """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        // Act
        var result = ReihitsuFormatter.FormatSyntaxTree(tree, TestContext.CancellationTokenSource.Token);
        var actual = result.GetRoot(TestContext.CancellationTokenSource.Token).ToFullString();

        // Assert
        Assert.AreEqual(expected, actual, "Output should preserve LF line endings and full formatted content.");
    }

    /// <summary>
    /// Verifies that <see cref="ReihitsuFormatter.FormatSyntaxTree"/> throws <see cref="OperationCanceledException"/> when cancellation is requested
    /// </summary>
    [TestMethod]
    public void FormatSyntaxTreeCancellationRequestedThrowsOperationCanceled()
    {
        // Arrange
        var input = CrLf("""
                         namespace Test;

                         public class Foo
                         {
                             public int Bar()
                             {
                                 var x = 1;
                                 return x;
                             }
                         }
                         """);

        var tree = CSharpSyntaxTree.ParseText(input, cancellationToken: TestContext.CancellationTokenSource.Token);

        using (var cts = new System.Threading.CancellationTokenSource())
        {
            cts.Cancel();

            Assert.ThrowsExactly<OperationCanceledException>(() => ReihitsuFormatter.FormatSyntaxTree(tree, cts.Token));
        }
    }

    /// <summary>
    /// Normalizes line endings in the provided text to LF
    /// </summary>
    /// <param name="text">The text to normalize</param>
    /// <returns>The text with LF line endings</returns>
    private static string Lf(string text)
    {
        return text.Replace("\r\n", "\n");
    }

    /// <summary>
    /// Normalizes line endings in the provided text to CRLF
    /// </summary>
    /// <param name="text">The text to normalize</param>
    /// <returns>The text with CRLF line endings</returns>
    private static string CrLf(string text)
    {
        return Lf(text).Replace("\n", "\r\n");
    }

    #endregion // Methods
}